// g2_define_status.h : header file
//

#ifndef _G2_DEFINE_STATUS_H_
#define _G2_DEFINE_STATUS_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "g2_define.h"
#include "g2_define_monitor.h"
#include "g2_define_product.h"

#ifdef __cplusplus
extern "C" {
#endif

//////////////////////////////////////////////////////////////////////////

struct G2STATUS_CALLBACK {
    enum TYPE {
        on_connected = 0,
        on_disconnected = 1,
        on_receive_instant_recording_start = 7,
        on_receive_instant_recording_stop = 8,
        on_receive_instant_recording_status = 9,
        on_receive_status = 2,
        on_receive_callback_event = 3,
        on_receive_log_system = 4,
        on_receive_log_event = 5,
        on_receive_log_debug = 6,
        
        CALLBACK_COUNT = 10
    };
};

//////////////////////////////////////////////////////////////////////////

struct G2STATUS_SUPPORT {
    enum QUERY {
        SUPPORT_LOG_SYSTEM = 1,
        SUPPORT_LOG_EVENT  = 2,
        SUPPORT_LOG_DEBUG  = 3,
        SUPPORT_LOG_G2     = 4,
        SUPPORT_INSTANT_RECORDING = 63
    };
};

//////////////////////////////////////////////////////////////////////////

struct G2STATUS_LOG_SEARCH_OPTIONS
{
    enum TYPE {
        TYPE_UNDEFINED = 0,
        TYPE_SYSTEM = 1,
        TYPE_EVENT,
        TYPE_DEBUG,
    };
    enum RESULT {
        SUCCESS = 0,
        FAIL,
        NO_MORE,
        LOADING,
        NOT_CONNECTED,
        NOT_SUPPORT
    };

    G2TIME _from;
    G2TIME _to;
    int    _type;
    bool   _reload;
};

struct G2STATUS_LOG
{
    enum G1_SYSTEM_LOG {
        SYSTEM_LOG_UNKNOWN = 0,
        SYSTEM_LOG_BOOT_UP = 1,
        SYSTEM_LOG_SHUTDOWN,
        SYSTEM_LOG_RESTART,
        SYSTEM_LOG_LOCAL_UPGRADE,
        SYSTEM_LOG_LOCAL_UPGRADE_FAIL,
        SYSTEM_LOG_REMOTE_UPGRADE,
        SYSTEM_LOG_REMOTE_UPGRADE_FAIL,
        SYSTEM_LOG_POWER_FAILURE,
        SYSTEM_LOG_LOCAL_TIME_CHANGE,
        SYSTEM_LOG_LOCAL_TIME_ZONE_CHANGE,
        SYSTEM_LOG_REMOTE_TIME_CHANGE,
        SYSTEM_LOG_REMOTE_TIME_ZONE_CHANGE,
        SYSTEM_LOG_TIME_SYNCED,
        SYSTEM_LOG_TIME_SYNC_FAILED,
        SYSTEM_LOG_DISK_BAD,
        SYSTEM_LOG_DISK_CONFIG_CHANGE,
        SYSTEM_LOG_DISK_ON,
        SYSTEM_LOG_DISK_OFF,
        SYSTEM_LOG_FACTORY_RESET,
        SYSTEM_LOG_HEATER_ON,
        SYSTEM_LOG_ACC_ON_OFF,
        SYSTEM_LOG_DISK_INFO,
        SYSTEM_LOG_DISK_REMOVED,
        SYSTEM_LOG_NO_STORAGE,
        SYSTEM_LOG_NOT_FORMATTED_STORAGE,
        SYSTEM_LOG_AUTO_FORMAT,
        SYSTEM_LOG_KEY_ON_OFF,
        SYSTEM_LOG_SHUTOFF,
        SYSTEM_LOG_LOCAL_LOGIN = 100,
        SYSTEM_LOG_LOCAL_LOGOUT,
        SYSTEM_LOG_REMOTE_LOGIN,
        SYSTEM_LOG_REMOTE_LOGOUT,
        SYSTEM_LOG_PASSWORD_MISMATCH,
        SYSTEM_LOG_PASSWORD_CHANGED_BY_AUTHENTICATION,
        SYSTEM_LOG_LOCAL_SETUP_BEGIN = 200,
        SYSTEM_LOG_LOCAL_SETUP_END,
        SYSTEM_LOG_REMOTE_SETUP_CHANGE,
        SYSTEM_LOG_REMOTE_SETUP_FAIL,
        SYSTEM_LOG_SETUP_IMPORTED,
        SYSTEM_LOG_SETUP_IMPORT_FAIL,
        SYSTEM_LOG_SETUP_EXPORTED,
        SYSTEM_LOG_SETUP_EXPORT_FAIL,
        SYSTEM_LOG_SETUP_EXPORT_CANCEL,
        SYSTEM_LOG_LOCAL_SETUP_CHANGE,
        SYSTEM_LOG_SCHEDULE_ON = 300,
        SYSTEM_LOG_SCHEDULE_OFF,
        SYSTEM_LOG_PANIC_ON,
        SYSTEM_LOG_PANIC_OFF,
        SYSTEM_LOG_LOCAL_CLEAR_ALL_DATA,
        SYSTEM_LOG_REMOTE_CLEAR_ALL_DATA,
        SYSTEM_LOG_CLEAR_DISK,
        SYSTEM_LOG_FORMAT_DISK,
        SYSTEM_LOG_TANGO_FULL,
        SYSTEM_LOG_AUTO_DELETION,
        SYSTEM_LOG_ARCHIVE_ON,
        SYSTEM_LOG_ARCHIVE_OFF,
        SYSTEM_LOG_AUTO_DELETION_ARCHIVE,
        SYSTEM_LOG_REMOTE_FORMAT_DISK,
        SYSTEM_LOG_LOCAL_SEARCH_BEGIN = 400,
        SYSTEM_LOG_LOCAL_SEARCH_END,
        SYSTEM_LOG_REMOTE_SEARCH_BEGIN,
        SYSTEM_LOG_REMOTE_SEARCH_END,
        SYSTEM_LOG_LOCAL_CLIP_COPY_BEGIN = 500,
        SYSTEM_LOG_LOCAL_CLIP_COPY_END,
        SYSTEM_LOG_LOCAL_CLIP_COPY_CANCEL,
        SYSTEM_LOG_LOCAL_CLIP_COPY_FAIL,
        SYSTEM_LOG_REMOTE_CLIP_COPY_BEGIN,
        SYSTEM_LOG_REMOTE_CLIP_COPY_END,
        SYSTEM_LOG_REMOTE_CLIP_COPY_CANCEL,
        SYSTEM_LOG_REMOTE_CLIP_COPY_FAIL,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_USER,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_FROM_TIME,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_TO_TIME,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_DURATION,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_EXPORT_TIME,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_CAMERA_TITLE,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_USER,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_FROM_TIME,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_TO_TIME,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_DURATION,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_EXPORT_TIME,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_CAMERA_TITLE,
        SYSTEM_LOG_LOCAL_CLIP_COPY_INFO_SITE_NAME,
        SYSTEM_LOG_REMOTE_CLIP_COPY_INFO_SITE_NAME,
        SYSTEM_LOG_CLIP_COPY_ARCHIVE_EXPORTED,
        SYSTEM_LOG_CLIP_COPY_ARCHIVE_EXPORT_FAIL,
        SYSTEM_LOG_CLIP_COPY_ARCHIVE_EXPORT_CANCEL,
        SYSTEM_LOG_CALLBACK_FAIL = 600,
        SYSTEM_LOG_WATCH_CLIENT_CONNECTED,
        SYSTEM_LOG_WATCH_CLIENT_DISCONNECTED,
        SYSTEM_LOG_WATCH_CLIENT_CONNECT_FAILED,
        SYSTEM_LOG_AUDIO_CLIENT_CONNECTED,
        SYSTEM_LOG_AUDIO_CLIENT_DISCONNECTED,
        SYSTEM_LOG_AUDIO_CLIENT_CONNECT_FAILED,
        SYSTEM_LOG_FTP_UPLOAD_FAIL,
        SYSTEM_LOG_FTP_UPLOAD_OK,
        SYSTEM_LOG_UPNP_OK = 610,
        SYSTEM_LOG_UPNP_PORT_CHANGED,
        SYSTEM_LOG_UPNP_ERROR_NO_IGD,
        SYSTEM_LOG_UPNP_ERROR_NETWORK,
        SYSTEM_LOG_UPNP_ERROR_FULL,
        SYSTEM_LOG_UPNP_ERROR_CONFLICT,
        SYSTEM_LOG_PUSH_NOTIFICATION_FAIL = 620,
        SYSTEM_LOG_NETFS_CONNECTED,
        SYSTEM_LOG_NETFS_DISCONNECTED,
        SYSTEM_LOG_LOCAL_OTP_SESSION_START = 630,
        SYSTEM_LOG_LOCAL_OTP_SESSION_CANCEL,
        SYSTEM_LOG_LOCAL_OTP_SESSION_FINISH,
        SYSTEM_LOG_REMOTE_OTP_SESSION_START,
        SYSTEM_LOG_REMOTE_OTP_SESSION_CANCEL,
        SYSTEM_LOG_REMOTE_OTP_SESSION_FINISH,
        SYSTEM_LOG_NETWORK_CAMERA_REBOOT = 640,
        SYSTEM_LOG_PRINT_BEGIN = 700,
        SYSTEM_LOG_PRINT_END,
        SYSTEM_LOG_PRINT_CANCEL,
        SYSTEM_LOG_MIRROR_1_START = 800,
        SYSTEM_LOG_MIRROR_1_START_FAIL,
        SYSTEM_LOG_MIRROR_1_STOP,
        SYSTEM_LOG_MIRROR_1_STOP_FAIL,
        SYSTEM_LOG_MIRROR_2_START,
        SYSTEM_LOG_MIRROR_2_START_FAIL,
        SYSTEM_LOG_MIRROR_2_STOP,
        SYSTEM_LOG_MIRROR_2_STOP_FAIL,
        SYSTEM_LOG_RESCHEDULE_START = 900,
        SYSTEM_LOG_RESCHEDULE_STOP,
        SYSTEM_LOG_SEQUENCE_ON = 1000,
        SYSTEM_LOG_SEQUENCE_OFF,
        SYSTEM_LOG_EVENT_MONITORING_ENABLED,
        SYSTEM_LOG_EVENT_MONITORING_DISABLED,
        SYSTEM_LOG_ALARM_AUDIO_IMPORT_FAIL = 1100,
        SYSTEM_LOG_ALARM_AUDIO_IMPORTED,
        SYSTEM_LOG_ALARM_AUDIO_EXPORT_FAIL,
        SYSTEM_LOG_ALARM_AUDIO_EXPORTED,
        SYSTEM_LOG_ALARM_AUDIO_EXPORT_CANCEL,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_BEGIN = 1200,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_END,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_CANCEL,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_FAIL,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_INFO_INFO_USER,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_INFO_FROM_TIME,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_INFO_TO_TIME,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_INFO_DURATION,
        SYSTEM_LOG_PARTIAL_DATA_ERASE_INFO_CAMERA_TITLE,
        SYSTEM_LOG_SYSTEM_LOG_EXPORTED = 1300,
        SYSTEM_LOG_SYSTEM_LOG_EXPORT_FAIL,
        SYSTEM_LOG_SYSTEM_LOG_EXPORT_CANCEL,
        SYSTEM_LOG_NETWORK_CAMERA_UPGRADE_BEGIN = 1400,
        SYSTEM_LOG_NETWORK_CAMERA_UPGRADE_END,
        SYSTEM_LOG_NETWORK_CAMERA_UPGRADE_FAIL,
        SYSTEM_LOG_NETWORK_CAMERA_UPGRADE_INFO_USER,
        SYSTEM_LOG_NETWORK_CAMERA_UPGRADE_INFO_TITLE,
        SYSTEM_LOG_NETWORK_CAMERA_REGISTER_BEGIN,
        SYSTEM_LOG_NETWORK_CAMERA_REGISTER_END,
        SYSTEM_LOG_NETWORK_CAMERA_REGISTER_FAIL,
        SYSTEM_LOG_NETWORK_CAMERA_REGISTER_CANCEL,
        SYSTEM_LOG_EQUALIZER_INITIALIZE_ALL_CHANNEL = 1500,
        SYSTEM_LOG_EQUALIZER_INITIALIZE_EACH_CHANNEL,
        SYSTEM_LOG_SECOM_FS_CONNECTED = 11000,
        SYSTEM_LOG_SECOM_FS_DISCONNECTED,
        SYSTEM_LOG_SECOM_HOST_CONNECTED = 11100,
        SYSTEM_LOG_SECOM_HOST_DISCONNECTED,
    };
    enum G2_LOG_TYPE_SYSTEM {
        G2_LOG_TYPE_SYSTEM_GENERAL                      = 10100000,
        G2_LOG_TYPE_SYSTEM_GENERAL_SYSTEM_BOOT_UP       = 10100001,
        G2_LOG_TYPE_SYSTEM_GENERAL_SYSTEM_SHUT_DOWN     = 10100002,
        G2_LOG_TYPE_SYSTEM_GENERAL_SYSTEM_RESTART       = 10100003,
        G2_LOG_TYPE_SYSTEM_GENERAL_POWER_FAILURE        = 10100004,
        G2_LOG_TYPE_SYSTEM_GENERAL_FACTORY_RESET_WOIPMODE = 10100005,
        G2_LOG_TYPE_SYSTEM_GENERAL_SHUTOFF              = 10100006,
        G2_LOG_TYPE_SYSTEM_GENERAL_FACTORY_RESET_WONET  = 10100007,
        G2_LOG_TYPE_SYSTEM_GENERAL_RESET_ADMIN_PASSWORD = 10100008,
        G2_LOG_TYPE_SYSTEM_USER                         = 10200000,
        G2_LOG_TYPE_SYSTEM_USER_LOCAL_LOGIN             = 10200001,
        G2_LOG_TYPE_SYSTEM_USER_LOCAL_LOGOUT            = 10200002,
        G2_LOG_TYPE_SYSTEM_USER_REMOTE_LOGIN            = 10200003,
        G2_LOG_TYPE_SYSTEM_USER_REMOTE_LOGOUT           = 10200004,
        G2_LOG_TYPE_SYSTEM_USER_PASSWORD_MISMATCH       = 10200005,
        G2_LOG_TYPE_SYSTEM_USER_PASSWORD_CHANGED_BY_AUTHENTICATION  = 10200006,
        G2_LOG_TYPE_SYSTEM_UPGRADE                      = 10300000,
        G2_LOG_TYPE_SYSTEM_LOCAL_UPGRADE                = 10300001,
        G2_LOG_TYPE_SYSTEM_LOCAL_UPGRADE_FAILED         = 10300002,
        G2_LOG_TYPE_SYSTEM_REMOTE_UPGRADE               = 10300003,
        G2_LOG_TYPE_SYSTEM_REMOTE_UPGRADE_FAILED        = 10300004,
        G2_LOG_TYPE_SYSTEM_TIME                         = 10400000,
        G2_LOG_TYPE_SYSTEM_LOCAL_TIME_CHANGE            = 10400001,
        G2_LOG_TYPE_SYSTEM_LOCAL_TIME_ZONE_CHANGE       = 10400002,
        G2_LOG_TYPE_SYSTEM_REMOTE_TIME_CHANGE           = 10400003,
        G2_LOG_TYPE_SYSTEM_REMOTE_TIME_ZONE_CHANGE      = 10400004,
        G2_LOG_TYPE_SYSTEM_TIME_SYNCED                  = 10400005,
        G2_LOG_TYPE_SYSTEM_TIME_SYNC_FAILED             = 10400006,
        G2_LOG_TYPE_SYSTEM_SETUP                        = 10500000,
        G2_LOG_TYPE_SYSTEM_LOCAL_SETUP_BEGIN            = 10500001,
        G2_LOG_TYPE_SYSTEM_LOCAL_SETUP_END              = 10500002,
        G2_LOG_TYPE_SYSTEM_LOCAL_SETUP_CHANGE           = 10500003,
        G2_LOG_TYPE_SYSTEM_REMOTE_SETUP_CHANGE          = 10500004,
        G2_LOG_TYPE_SYSTEM_REMOTE_SETUP_FAILED          = 10500005,
        G2_LOG_TYPE_SYSTEM_SETUP_IMPORTED               = 10500006,
        G2_LOG_TYPE_SYSTEM_SETUP_IMPORT_FAILED          = 10500007,
        G2_LOG_TYPE_SYSTEM_SETUP_EXPORTED               = 10500008,
        G2_LOG_TYPE_SYSTEM_SETUP_EXPORT_FAILED          = 10500009,
        G2_LOG_TYPE_SYSTEM_SETUP_EXPORT_CANCELED        = 10500010,
        G2_LOG_TYPE_SYSTEM_NETWORK                      = 10600000,
        G2_LOG_TYPE_SYSTEM_NETWORK_FEN                  = 10601000,
        G2_LOG_TYPE_SYSTEM_NETWORK_FEN_NOTIFY_OK        = 10601001,
        G2_LOG_TYPE_SYSTEM_NETWORK_FEN_NOTIFY_FAILED    = 10601002,
        G2_LOG_TYPE_SYSTEM_NETWORK_UPNP                 = 10602000,
        G2_LOG_TYPE_SYSTEM_NETWORK_UPNP_REGISTER_OK     = 10602001,
        G2_LOG_TYPE_SYSTEM_NETWORK_UPNP_REGISTER_NEW_PORT = 10602002,
        G2_LOG_TYPE_SYSTEM_NETWORK_UPNP_REGISTER_FAILED = 10602003,
        G2_LOG_TYPE_SYSTEM_NETWORK_DIRECTIP             = 10603000,
        G2_LOG_TYPE_SYSTEM_NETWORK_DIRECTIP_RESET_REGISTRATION   = 10603001,
        G2_LOG_TYPE_SYSTEM_NETWORK_DIRECTIP_SWITCHED_TO_DIRECTIP = 10603002,
        G2_LOG_TYPE_SYSTEM_NETWORK_DIRECTIP_SWITCHED_TO_OPENIP   = 10603003,
        G2_LOG_TYPE_SYSTEM_NETWORK_TCP_CALLBACK         = 10604000,
        G2_LOG_TYPE_SYSTEM_NETWORK_TCP_CALLBACK_OK      = 10604001,
        G2_LOG_TYPE_SYSTEM_NETWORK_TCP_CALLBACK_FAILED  = 10604002,
        G2_LOG_TYPE_SYSTEM_NETWORK_EMAIL                = 10605000,
        G2_LOG_TYPE_SYSTEM_NETWORK_EMAIL_SEND_OK        = 10605001,
        G2_LOG_TYPE_SYSTEM_NETWORK_EMAIL_SEND_FAILED    = 10605002,
        G2_LOG_TYPE_SYSTEM_NETWORK_FTP                  = 10606000,
        G2_LOG_TYPE_SYSTEM_NETWORK_FTP_UPLOAD_OK        = 10606001,
        G2_LOG_TYPE_SYSTEM_NETWORK_FTP_UPLOAD_FAILED    = 10606002,
        G2_LOG_TYPE_SYSTEM_NETWORK_CLOUD                = 10607000,
        G2_LOG_TYPE_SYSTEM_NETWORK_CLOUD_UPLOAD_OK      = 10607001,
        G2_LOG_TYPE_SYSTEM_NETWORK_CLOUD_UPLOAD_FAILED  = 10607002
    };
    enum G2_LOG_TYPE_DEBUG {
        G2_LOG_TYPE_DEBUG_GENERAL                      = 20100000
    };

    enum RESULT {
        SUCCESS = 0,
        FAIL,
        NO_MORE,
        LOADING,
        NOT_CONNECTED,
        NOT_SUPPORT
    };
};

struct G2STATUS_LOG_SYSTEM
{
    enum VERSION {
        VERSION_LEGACY = 0,
        VERSION_IDR,
        VERSION_G1,
        VERSION_G2
    };

    unsigned char _version;
    unsigned int  _type;
    G2TIME        _time;
    G2STRING_128  _label;
    signed char   _data[32];
};

struct G2STATUS_LOG_EVENT
{
    enum VERSION {
        VERSION_LEGACY = 0,
        VERSION_IDR,
        VERSION_G1,
        VERSION_G2
    };

    unsigned char _version;
    int           _level1;
    int           _level2;
    G2TIME        _time;
    G2STRING_64   _event;
    G2STRING_128  _label;
    signed char   _data[32];
};

//////////////////////////////////////////////////////////////////////////

#ifdef __cplusplus
}
#endif

#endif // !_G2_DEFINE_STATUS_H_
