[Server Connection Info]
siteid=100

[SDMS]
update_src=c:\temp\new
update_trg=c:\temp\update
update_temp=c:\temp\temp

[Monitor]
title="e-재난 서버관리자"
checkTime=30
termserverip="192.168.0.195"
# 192.168.0.195 연결문자열
termconn="aWSj98oP0X1OaoMgFvSkAAp87mok795XYwmsQYiekTc="


[Server Info]
server=SOPServer,AsinFire,Access,SVMS,Empoll,SensorServer

[SOPServer]
ID=1
Path="C:\EDU_100"
File="SOPServer.exe"
Name="SOPServer"
ShortName="SOP서버"
Service = 0

[AsinFire]
ID=2
Path="C:\EDU_100"
File="ExternalFireSensorDBWatcher.exe"
Name="ExternalFireSensorDBWatcher"
ShortName="화재서버"
Service = 0

[Access]
ID=3
Path="C:\EDU_100"
File="AccessSecurityServer.exe"
Name="AccessSecurityServer"
ShortName="Access서버"
Service = 0

[SVMS]
ID=4
Path="C:\EDU_100"
File="SVMSEventReciver.exe"
Name="SVMSEventReciver"
ShortName="SVMS서버"
Service = 0


[Empoll]
ID=5
Path="C:\EDU_100"
File="CCTVAlarmWatcher.exe"
Name="CCTVAlarmWatcher"
ShortName="비상벨서버"
Service = 0

[SensorServer]
ID=6
Path="c:\EDU_100"
File="S1SensorServer.exe"
Name="S1SensorServer"
ShortName="테스트서버"
Service = 0
