/*
 * This code was generated by FormatTemplate as part of the build process. Do not edit it.
 *
 * Generated on 2014-06-12 05:09:14.
 *
 */

namespace IronPython {
    public static class CurrentVersion {
        public const int Major = 2;
        public const int Minor = 7;
        public const int Micro = 4;
        public const string ReleaseLevel = "final";
        public const int ReleaseSerial = 0;

        public const string ShortReleaseLevel = "f";

        public const string Series = "2.7";
        public const string DisplayVersion = "2.7.4";
        public const string DisplayName = "IronPython 2.7.4";

#if !SILVERLIGHT
        public const string AssemblyVersion = "2.7.0.40";
#else
        public const string AssemblyVersion = "2.7.1300.40";
#endif
        
        public const string AssemblyFileVersion = "2.7.4.1000";
        public const string AssemblyInformationalVersion = "IronPython 2.7.4 final 0";
    }
}