//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.18444에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace SenarioWeb.SenarioService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PreSafeSoap", Namespace="http://unes.iptime.org/presafe")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class PreSafe : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SenarioListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SenarioListForTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunSenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunSenario2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSenarioDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadSenarioDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PreSafe() {
            this.Url = global::SenarioWeb.Properties.Settings.Default.SenarioWeb_SenarioService_PreSafe;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SenarioListCompletedEventHandler SenarioListCompleted;
        
        /// <remarks/>
        public event SenarioListForTypeCompletedEventHandler SenarioListForTypeCompleted;
        
        /// <remarks/>
        public event RunSenarioCompletedEventHandler RunSenarioCompleted;
        
        /// <remarks/>
        public event RunSenario2CompletedEventHandler RunSenario2Completed;
        
        /// <remarks/>
        public event SaveSenarioDataCompletedEventHandler SaveSenarioDataCompleted;
        
        /// <remarks/>
        public event LoadSenarioDataCompletedEventHandler LoadSenarioDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unes.iptime.org/presafe/SenarioList", RequestNamespace="http://unes.iptime.org/presafe", ResponseNamespace="http://unes.iptime.org/presafe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SenarioList() {
            object[] results = this.Invoke("SenarioList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SenarioListAsync() {
            this.SenarioListAsync(null);
        }
        
        /// <remarks/>
        public void SenarioListAsync(object userState) {
            if ((this.SenarioListOperationCompleted == null)) {
                this.SenarioListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSenarioListOperationCompleted);
            }
            this.InvokeAsync("SenarioList", new object[0], this.SenarioListOperationCompleted, userState);
        }
        
        private void OnSenarioListOperationCompleted(object arg) {
            if ((this.SenarioListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SenarioListCompleted(this, new SenarioListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unes.iptime.org/presafe/SenarioListForType", RequestNamespace="http://unes.iptime.org/presafe", ResponseNamespace="http://unes.iptime.org/presafe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SenarioListForType(int[] nType) {
            object[] results = this.Invoke("SenarioListForType", new object[] {
                        nType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SenarioListForTypeAsync(int[] nType) {
            this.SenarioListForTypeAsync(nType, null);
        }
        
        /// <remarks/>
        public void SenarioListForTypeAsync(int[] nType, object userState) {
            if ((this.SenarioListForTypeOperationCompleted == null)) {
                this.SenarioListForTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSenarioListForTypeOperationCompleted);
            }
            this.InvokeAsync("SenarioListForType", new object[] {
                        nType}, this.SenarioListForTypeOperationCompleted, userState);
        }
        
        private void OnSenarioListForTypeOperationCompleted(object arg) {
            if ((this.SenarioListForTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SenarioListForTypeCompleted(this, new SenarioListForTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unes.iptime.org/presafe/RunSenario", RequestNamespace="http://unes.iptime.org/presafe", ResponseNamespace="http://unes.iptime.org/presafe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RunSenario(string senarioName, bool bUseSound, float nSoundLevel, bool bUseHeartBeat, int nHeartBeat, bool bUseAlcole, float nAlcole, bool bUseVelocity, float nVelocity, bool bUseAcc, float nAccelate, bool bUseLocation, int nLocation, bool bUseImpact, bool bImpact) {
            object[] results = this.Invoke("RunSenario", new object[] {
                        senarioName,
                        bUseSound,
                        nSoundLevel,
                        bUseHeartBeat,
                        nHeartBeat,
                        bUseAlcole,
                        nAlcole,
                        bUseVelocity,
                        nVelocity,
                        bUseAcc,
                        nAccelate,
                        bUseLocation,
                        nLocation,
                        bUseImpact,
                        bImpact});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void RunSenarioAsync(string senarioName, bool bUseSound, float nSoundLevel, bool bUseHeartBeat, int nHeartBeat, bool bUseAlcole, float nAlcole, bool bUseVelocity, float nVelocity, bool bUseAcc, float nAccelate, bool bUseLocation, int nLocation, bool bUseImpact, bool bImpact) {
            this.RunSenarioAsync(senarioName, bUseSound, nSoundLevel, bUseHeartBeat, nHeartBeat, bUseAlcole, nAlcole, bUseVelocity, nVelocity, bUseAcc, nAccelate, bUseLocation, nLocation, bUseImpact, bImpact, null);
        }
        
        /// <remarks/>
        public void RunSenarioAsync(
                    string senarioName, 
                    bool bUseSound, 
                    float nSoundLevel, 
                    bool bUseHeartBeat, 
                    int nHeartBeat, 
                    bool bUseAlcole, 
                    float nAlcole, 
                    bool bUseVelocity, 
                    float nVelocity, 
                    bool bUseAcc, 
                    float nAccelate, 
                    bool bUseLocation, 
                    int nLocation, 
                    bool bUseImpact, 
                    bool bImpact, 
                    object userState) {
            if ((this.RunSenarioOperationCompleted == null)) {
                this.RunSenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunSenarioOperationCompleted);
            }
            this.InvokeAsync("RunSenario", new object[] {
                        senarioName,
                        bUseSound,
                        nSoundLevel,
                        bUseHeartBeat,
                        nHeartBeat,
                        bUseAlcole,
                        nAlcole,
                        bUseVelocity,
                        nVelocity,
                        bUseAcc,
                        nAccelate,
                        bUseLocation,
                        nLocation,
                        bUseImpact,
                        bImpact}, this.RunSenarioOperationCompleted, userState);
        }
        
        private void OnRunSenarioOperationCompleted(object arg) {
            if ((this.RunSenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunSenarioCompleted(this, new RunSenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unes.iptime.org/presafe/RunSenario2", RequestNamespace="http://unes.iptime.org/presafe", ResponseNamespace="http://unes.iptime.org/presafe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RunSenario2(string senarioName, bool bUseLocation, int nLocation, bool bUseHeartBeat, int nHeartBeat, bool bUseAcc, int nAcc, bool bUseAlcohol, int nAlcohol, bool bUseSound, int nSound, bool bUseImpact, int nImpact) {
            object[] results = this.Invoke("RunSenario2", new object[] {
                        senarioName,
                        bUseLocation,
                        nLocation,
                        bUseHeartBeat,
                        nHeartBeat,
                        bUseAcc,
                        nAcc,
                        bUseAlcohol,
                        nAlcohol,
                        bUseSound,
                        nSound,
                        bUseImpact,
                        nImpact});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void RunSenario2Async(string senarioName, bool bUseLocation, int nLocation, bool bUseHeartBeat, int nHeartBeat, bool bUseAcc, int nAcc, bool bUseAlcohol, int nAlcohol, bool bUseSound, int nSound, bool bUseImpact, int nImpact) {
            this.RunSenario2Async(senarioName, bUseLocation, nLocation, bUseHeartBeat, nHeartBeat, bUseAcc, nAcc, bUseAlcohol, nAlcohol, bUseSound, nSound, bUseImpact, nImpact, null);
        }
        
        /// <remarks/>
        public void RunSenario2Async(string senarioName, bool bUseLocation, int nLocation, bool bUseHeartBeat, int nHeartBeat, bool bUseAcc, int nAcc, bool bUseAlcohol, int nAlcohol, bool bUseSound, int nSound, bool bUseImpact, int nImpact, object userState) {
            if ((this.RunSenario2OperationCompleted == null)) {
                this.RunSenario2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunSenario2OperationCompleted);
            }
            this.InvokeAsync("RunSenario2", new object[] {
                        senarioName,
                        bUseLocation,
                        nLocation,
                        bUseHeartBeat,
                        nHeartBeat,
                        bUseAcc,
                        nAcc,
                        bUseAlcohol,
                        nAlcohol,
                        bUseSound,
                        nSound,
                        bUseImpact,
                        nImpact}, this.RunSenario2OperationCompleted, userState);
        }
        
        private void OnRunSenario2OperationCompleted(object arg) {
            if ((this.RunSenario2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunSenario2Completed(this, new RunSenario2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unes.iptime.org/presafe/SaveSenarioData", RequestNamespace="http://unes.iptime.org/presafe", ResponseNamespace="http://unes.iptime.org/presafe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveSenarioData(string szDeviceID, int nDeviceType, bool bUseLocation, int nLocation, bool bUseHeartBeat, int nHeartBeat, bool bUseAcc, int nAcc, bool bUseAlcohol, int nAlcohol, bool bUseSound, int nSound, bool bUseImpact, int nImpact, string szDescription) {
            object[] results = this.Invoke("SaveSenarioData", new object[] {
                        szDeviceID,
                        nDeviceType,
                        bUseLocation,
                        nLocation,
                        bUseHeartBeat,
                        nHeartBeat,
                        bUseAcc,
                        nAcc,
                        bUseAlcohol,
                        nAlcohol,
                        bUseSound,
                        nSound,
                        bUseImpact,
                        nImpact,
                        szDescription});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSenarioDataAsync(string szDeviceID, int nDeviceType, bool bUseLocation, int nLocation, bool bUseHeartBeat, int nHeartBeat, bool bUseAcc, int nAcc, bool bUseAlcohol, int nAlcohol, bool bUseSound, int nSound, bool bUseImpact, int nImpact, string szDescription) {
            this.SaveSenarioDataAsync(szDeviceID, nDeviceType, bUseLocation, nLocation, bUseHeartBeat, nHeartBeat, bUseAcc, nAcc, bUseAlcohol, nAlcohol, bUseSound, nSound, bUseImpact, nImpact, szDescription, null);
        }
        
        /// <remarks/>
        public void SaveSenarioDataAsync(
                    string szDeviceID, 
                    int nDeviceType, 
                    bool bUseLocation, 
                    int nLocation, 
                    bool bUseHeartBeat, 
                    int nHeartBeat, 
                    bool bUseAcc, 
                    int nAcc, 
                    bool bUseAlcohol, 
                    int nAlcohol, 
                    bool bUseSound, 
                    int nSound, 
                    bool bUseImpact, 
                    int nImpact, 
                    string szDescription, 
                    object userState) {
            if ((this.SaveSenarioDataOperationCompleted == null)) {
                this.SaveSenarioDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSenarioDataOperationCompleted);
            }
            this.InvokeAsync("SaveSenarioData", new object[] {
                        szDeviceID,
                        nDeviceType,
                        bUseLocation,
                        nLocation,
                        bUseHeartBeat,
                        nHeartBeat,
                        bUseAcc,
                        nAcc,
                        bUseAlcohol,
                        nAlcohol,
                        bUseSound,
                        nSound,
                        bUseImpact,
                        nImpact,
                        szDescription}, this.SaveSenarioDataOperationCompleted, userState);
        }
        
        private void OnSaveSenarioDataOperationCompleted(object arg) {
            if ((this.SaveSenarioDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSenarioDataCompleted(this, new SaveSenarioDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unes.iptime.org/presafe/LoadSenarioData", RequestNamespace="http://unes.iptime.org/presafe", ResponseNamespace="http://unes.iptime.org/presafe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] LoadSenarioData(string szDeviceID, int nDeviceType) {
            object[] results = this.Invoke("LoadSenarioData", new object[] {
                        szDeviceID,
                        nDeviceType});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadSenarioDataAsync(string szDeviceID, int nDeviceType) {
            this.LoadSenarioDataAsync(szDeviceID, nDeviceType, null);
        }
        
        /// <remarks/>
        public void LoadSenarioDataAsync(string szDeviceID, int nDeviceType, object userState) {
            if ((this.LoadSenarioDataOperationCompleted == null)) {
                this.LoadSenarioDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadSenarioDataOperationCompleted);
            }
            this.InvokeAsync("LoadSenarioData", new object[] {
                        szDeviceID,
                        nDeviceType}, this.LoadSenarioDataOperationCompleted, userState);
        }
        
        private void OnLoadSenarioDataOperationCompleted(object arg) {
            if ((this.LoadSenarioDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadSenarioDataCompleted(this, new LoadSenarioDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SenarioListCompletedEventHandler(object sender, SenarioListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SenarioListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SenarioListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SenarioListForTypeCompletedEventHandler(object sender, SenarioListForTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SenarioListForTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SenarioListForTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RunSenarioCompletedEventHandler(object sender, RunSenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunSenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunSenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RunSenario2CompletedEventHandler(object sender, RunSenario2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunSenario2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunSenario2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveSenarioDataCompletedEventHandler(object sender, SaveSenarioDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSenarioDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSenarioDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoadSenarioDataCompletedEventHandler(object sender, LoadSenarioDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadSenarioDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadSenarioDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591