//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUtility2.UploadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UploadService.IUpload")]
    public interface IUpload {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/Upload", ReplyAction="http://tempuri.org/IUpload/UploadResponse")]
        string Upload(string fileName, byte[] bytes, bool isFirst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/Upload", ReplyAction="http://tempuri.org/IUpload/UploadResponse")]
        System.Threading.Tasks.Task<string> UploadAsync(string fileName, byte[] bytes, bool isFirst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/Upload2", ReplyAction="http://tempuri.org/IUpload/Upload2Response")]
        string Upload2(string fileName, byte[] bytes, bool isFirst, string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/Upload2", ReplyAction="http://tempuri.org/IUpload/Upload2Response")]
        System.Threading.Tasks.Task<string> Upload2Async(string fileName, byte[] bytes, bool isFirst, string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/GetMaxSegmentSize", ReplyAction="http://tempuri.org/IUpload/GetMaxSegmentSizeResponse")]
        int GetMaxSegmentSize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/GetMaxSegmentSize", ReplyAction="http://tempuri.org/IUpload/GetMaxSegmentSizeResponse")]
        System.Threading.Tasks.Task<int> GetMaxSegmentSizeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveFile", ReplyAction="http://tempuri.org/IUpload/RemoveFileResponse")]
        string RemoveFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveFile", ReplyAction="http://tempuri.org/IUpload/RemoveFileResponse")]
        System.Threading.Tasks.Task<string> RemoveFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveFile2", ReplyAction="http://tempuri.org/IUpload/RemoveFile2Response")]
        string RemoveFile2(string fileName, string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveFile2", ReplyAction="http://tempuri.org/IUpload/RemoveFile2Response")]
        System.Threading.Tasks.Task<string> RemoveFile2Async(string fileName, string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveAll", ReplyAction="http://tempuri.org/IUpload/RemoveAllResponse")]
        string RemoveAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveAll", ReplyAction="http://tempuri.org/IUpload/RemoveAllResponse")]
        System.Threading.Tasks.Task<string> RemoveAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveAll2", ReplyAction="http://tempuri.org/IUpload/RemoveAll2Response")]
        string RemoveAll2(string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/RemoveAll2", ReplyAction="http://tempuri.org/IUpload/RemoveAll2Response")]
        System.Threading.Tasks.Task<string> RemoveAll2Async(string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/ExtractToTrg", ReplyAction="http://tempuri.org/IUpload/ExtractToTrgResponse")]
        string ExtractToTrg(string strSrcFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/ExtractToTrg", ReplyAction="http://tempuri.org/IUpload/ExtractToTrgResponse")]
        System.Threading.Tasks.Task<string> ExtractToTrgAsync(string strSrcFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/ExtractToTrg2", ReplyAction="http://tempuri.org/IUpload/ExtractToTrg2Response")]
        string ExtractToTrg2(string strSrcFile, string strTrgPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpload/ExtractToTrg2", ReplyAction="http://tempuri.org/IUpload/ExtractToTrg2Response")]
        System.Threading.Tasks.Task<string> ExtractToTrg2Async(string strSrcFile, string strTrgPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadChannel : DBUtility2.UploadService.IUpload, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadClient : System.ServiceModel.ClientBase<DBUtility2.UploadService.IUpload>, DBUtility2.UploadService.IUpload {
        
        public UploadClient() {
        }
        
        public UploadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Upload(string fileName, byte[] bytes, bool isFirst) {
            return base.Channel.Upload(fileName, bytes, isFirst);
        }
        
        public System.Threading.Tasks.Task<string> UploadAsync(string fileName, byte[] bytes, bool isFirst) {
            return base.Channel.UploadAsync(fileName, bytes, isFirst);
        }
        
        public string Upload2(string fileName, byte[] bytes, bool isFirst, string folderPath) {
            return base.Channel.Upload2(fileName, bytes, isFirst, folderPath);
        }
        
        public System.Threading.Tasks.Task<string> Upload2Async(string fileName, byte[] bytes, bool isFirst, string folderPath) {
            return base.Channel.Upload2Async(fileName, bytes, isFirst, folderPath);
        }
        
        public int GetMaxSegmentSize() {
            return base.Channel.GetMaxSegmentSize();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxSegmentSizeAsync() {
            return base.Channel.GetMaxSegmentSizeAsync();
        }
        
        public string RemoveFile(string fileName) {
            return base.Channel.RemoveFile(fileName);
        }
        
        public System.Threading.Tasks.Task<string> RemoveFileAsync(string fileName) {
            return base.Channel.RemoveFileAsync(fileName);
        }
        
        public string RemoveFile2(string fileName, string folderPath) {
            return base.Channel.RemoveFile2(fileName, folderPath);
        }
        
        public System.Threading.Tasks.Task<string> RemoveFile2Async(string fileName, string folderPath) {
            return base.Channel.RemoveFile2Async(fileName, folderPath);
        }
        
        public string RemoveAll() {
            return base.Channel.RemoveAll();
        }
        
        public System.Threading.Tasks.Task<string> RemoveAllAsync() {
            return base.Channel.RemoveAllAsync();
        }
        
        public string RemoveAll2(string folderPath) {
            return base.Channel.RemoveAll2(folderPath);
        }
        
        public System.Threading.Tasks.Task<string> RemoveAll2Async(string folderPath) {
            return base.Channel.RemoveAll2Async(folderPath);
        }
        
        public string ExtractToTrg(string strSrcFile) {
            return base.Channel.ExtractToTrg(strSrcFile);
        }
        
        public System.Threading.Tasks.Task<string> ExtractToTrgAsync(string strSrcFile) {
            return base.Channel.ExtractToTrgAsync(strSrcFile);
        }
        
        public string ExtractToTrg2(string strSrcFile, string strTrgPath) {
            return base.Channel.ExtractToTrg2(strSrcFile, strTrgPath);
        }
        
        public System.Threading.Tasks.Task<string> ExtractToTrg2Async(string strSrcFile, string strTrgPath) {
            return base.Channel.ExtractToTrg2Async(strSrcFile, strTrgPath);
        }
    }
}
