//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by G2Client.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_G2CLIENT_TYPE               129
#define IDR_MENU_CAMERA_CONTEXT         130
#define IDR_MENU_SEARCH                 131
#define IDD_LOGIN_USER                  132
#define IDD_DEVICE_INFO                 133
#define IDD_DUMMY_CHILD                 134
#define IDD_DUMMY_POPUP                 135
#define IDD_CONTROLLER_WATCH            136
#define IDD_CONTROLLER_PLAY             137
#define IDD_CONTROLLER_SEARCH           138
#define IDD_CONTROLLER_LOG              139
#define IDD_GOTO_TIME                   140
#define IDD_SELECT_SEGMENT              141
#define IDD_PTZ_PRESET                  142
#define IDD_PTZ_ADVANCED                143
#define IDD_EVENT_CONDITION             144
#define IDD_PLAY_CALENDAR               145
#define IDD_PLAY_CLIPCOPY               146
#define IDD_PLAY_CLIPCOPY_PASSWORD      147
#define IDD_SELECT_SCOPE                148
#define IDC_CURSOR_HAND                 148
#define IDD_SELECT_EXTERNAL_TANGO       149
#define IDC_CURSOR_FINGER               150
#define IDC_CURSOR_GRIP                 151
#define IDD_SEARCH_CONDITION_TEXT_IN    152
#define IDD_SEARCH_CONDITION_EVENT      153
#define IDD_SEARCH_CONDITION            154
#define IDD_SEARCH_CONDITION_EVENT_IDR  155
#define IDD_SEARCH_EVENT_PROGRESS       156
#define IDD_VIOLET_INK                  157
#define IDD_VIOLET_LAYOUT               158
#define IDD_CONTROLLER_BACKUP           159
#define IDD_SELECT_BACKUP_SITE          160
#define IDD_CONTROLLER_SEARCH_G2        161
#define IDR_MENU_SEARCH_G2              162
#define IDD_STATUS                      163
#define IDC_LOGIN_STC_MESSAGE           1000
#define IDC_LOGIN_EDT_ADDRESS           1001
#define IDC_LOGIN_EDT_PORT              1002
#define IDC_LOGIN_EDT_ID                1003
#define IDC_LOGIN_EDT_PASSWORD          1004
#define IDC_CBX_SCREEN_FORMAT           1005
#define IDC_BTN_FULL_SCREEN             1006
#define IDC_BTN_PLAY_LAYOUT_PREV        1007
#define IDC_BTN_PLAY_LAYOUT_NEXT        1008
#define IDC_BTN_HOT_SPOT                1009
#define IDC_BTN_EVENT_SPOT              1010
#define IDC_BTN_EXPORT                  1011
#define IDC_BTN_SEQUENCE                1012
#define IDC_BTN_PLAY_GO_TO              1013
#define IDC_BTN_PLAY_CLIPCOPY           1014
#define IDC_BTN_PLAY_BACKWARD           1015
#define IDC_BTN_PLAY_FORWARD            1016
#define IDC_BTN_PLAY_MOVE_STEP          1017
#define IDC_SLD_PLAY_JOG_SHUTTLE        1018
#define IDC_STC_PLAY_JOG_SPEED          1019
#define IDC_BTN_PLAY_STOP               1020
#define IDC_BTN_PLAY_PLAY               1021
#define IDC_BTN_PLAY_CALENDAR           1022
#define IDC_CBX_PLAY_SCREEN_FORMAT      1023
#define IDC_PLAY_CALENDAR_CONTROL       1024
#define IDC_BTN_SEARCH_MODE             1025
#define IDC_BTN_SEARCH_FILTER           1026
#define IDC_BTN_SEARCH_CALENDAR         1027
#define IDC_BTN_SEARCH_GO_TO            1028
#define IDC_BTN_SEARCH_ADDITIONAL_MENU  1029
#define IDC_BTN_SEARCH_EXPORT_VIDEO     1030
#define IDC_BTN_SEARCH_REW              1031
#define IDC_BTN_SEARCH_PREV             1032
#define IDC_BTN_SEARCH_STOP             1033
#define IDC_BTN_SEARCH_PLAY             1034
#define IDC_BTN_SEARCH_NEXT             1035
#define IDC_BTN_SEARCH_FF               1036
#define IDC_SLD_SEARCH_SHUTTLE          1037
#define IDC_SLD_SEARCH_FAST_SHUTTLE     1038
#define IDC_STC_SEARCH_SHUTTLE_SPEED    1039
#define IDC_CBX_SEARCH_SCREEN_FORMAT    1040
#define IDC_BTN_SEARCH_LAYOUT_PREV      1041
#define IDC_BTN_SEARCH_LAYOUT_NEXT      1042
#define IDC_BTN_LAYOUT_PREV             1043
#define IDC_BTN_LAYOUT_NEXT             1044
#define IDC_GOTOTIME_DTP_TIME           1045
#define IDC_GOTOTIME_DTP_DATE           1046
#define IDC_LST_SELECT_SEGMENT          1047
#define IDC_STC_ZOOM                    1048
#define IDC_STC_FOCUS                   1049
#define IDC_STC_IRIS                    1050
#define IDC_BTN_PTZ_N                   1051
#define IDC_BTN_PTZ_NE                  1052
#define IDC_BTN_PTZ_E                   1053
#define IDC_BTN_PTZ_SE                  1054
#define IDC_BTN_PTZ_S                   1055
#define IDC_BTN_PTZ_SW                  1056
#define IDC_BTN_PTZ_W                   1057
#define IDC_BTN_PTZ_NW                  1058
#define IDC_BTN_PTZ_MENU                1059
#define IDC_BTN_PTZ_ZOOM_IN             1060
#define IDC_BTN_PTZ_ZOOM_OUT            1061
#define IDC_BTN_PTZ_FOCUS_FAR           1062
#define IDC_BTN_PTZ_FOCUS_NEAR          1063
#define IDC_BTN_PTZ_IRIS_OPEN           1064
#define IDC_BTN_PTZ_IRIS_CLOSE          1065
#define IDC_BTN_PTZ_SET_PRESET          1066
#define IDC_BTN_PTZ_VIEW_PRESET         1067
#define IDC_BTN_PTZ_ADVANCED            1068
#define IDC_STC_TITLE                   1069
#define IDC_EDT_TITLE                   1070
#define IDC_LST_PRESET                  1071
#define IDC_BTN_SPEED                   1072
#define IDC_BTN_TOUR                    1073
#define IDC_BTN_AUTO_PAN                1074
#define IDC_BTN_PATTERN                 1075
#define IDC_BTN_TOUR_NUMBER             1076
#define IDC_BTN_PATTERN_NUMBER          1077
#define IDC_BTN_DEVICE_MENU             1078
#define IDC_BTN_LIGHT                   1079
#define IDC_BTN_PUMP                    1080
#define IDC_BTN_WIPER                   1081
#define IDC_BTN_POWER                   1082
#define IDC_BTN_AUX                     1083
#define IDC_BTN_MOVE_ORIGIN             1084
#define IDC_CHK_CTRL                    1085
#define IDC_BTN_ENTER                   1086
#define IDC_BTN_ESC                     1087
#define IDC_DTP_FROM_DATE               1088
#define IDC_DTP_FROM_TIME               1089
#define IDC_DTP_TO_DATE                 1090
#define IDC_DTP_TO_TIME                 1091
#define IDC_CHK_FIRST                   1092
#define IDC_CHK_LAST                    1093
#define IDC_BTN_CONDITION               1094
#define IDC_BTN_SEARCH                  1095
#define IDC_BTN_MORE                    1096
#define IDC_STC_DEVICE_NAME             1097
#define IDC_STC_FROM                    1098
#define IDC_STC_TO                      1099
#define IDC_CBX_DEVICE                  1100
#define IDC_CHK_SAVE_PW                 1101
#define IDC_BTN_START_STOP              1102
#define IDC_EDT_PASSWORD                1103
#define IDC_PROGRESS_BAR                1104
#define IDC_LST_SELECT_EXTERNAL_TANGO   1105
#define IDC_RDO_MODE_EVENT              1107
#define IDC_RDO_MODE_TEXTIN             1108
#define IDC_SEARCH_CONDITION_DEVICE_TREE 1109
#define IDC_EDT_NAME_0                  1110
#define IDC_EDT_NAME_1                  1111
#define IDC_EDT_NAME_2                  1112
#define IDC_EDT_NAME_3                  1113
#define IDC_EDT_NAME_4                  1114
#define IDC_CBX_COMP_0                  1115
#define IDC_CBX_COMP_1                  1116
#define IDC_CBX_COMP_2                  1117
#define IDC_CBX_COMP_3                  1118
#define IDC_CBX_COMP_4                  1119
#define IDC_EDT_VALUE_0                 1120
#define IDC_EDT_VALUE_1                 1121
#define IDC_EDT_VALUE_2                 1122
#define IDC_EDT_VALUE_3                 1123
#define IDC_EDT_VALUE_4                 1124
#define IDC_EDT_COLUMN_0                1125
#define IDC_EDT_COLUMN_1                1126
#define IDC_EDT_COLUMN_2                1127
#define IDC_EDT_COLUMN_3                1128
#define IDC_EDT_COLUMN_4                1129
#define IDC_EDT_LINE_0                  1130
#define IDC_EDT_LINE_1                  1131
#define IDC_EDT_LINE_2                  1132
#define IDC_EDT_LINE_3                  1133
#define IDC_EDT_LINE_4                  1134
#define IDC_CBX_OPERATOR_1              1135
#define IDC_CBX_OPERATOR_2              1136
#define IDC_CBX_OPERATOR_3              1137
#define IDC_CBX_OPERATOR_4              1138
#define IDC_CHK_CASE_SENSTIVE           1139
#define IDC_CHK_MATCH_WORD              1140
#define IDC_CHK_TRANSACTION_WISE        1141
#define IDC_STC_SEARCH_TO               1142
#define IDC_STC_SEARCH_FROM             1143
#define IDC_CHK_SEARCH_FIRST            1144
#define IDC_CHK_SEARCH_LAST             1145
#define IDC_DTP_SEARCH_FROM_DATE        1146
#define IDC_DTP_SEARCH_FROM_TIME        1147
#define IDC_DTP_SEARCH_TO_DATE          1148
#define IDC_DTP_SEARCH_TO_TIME          1149
#define IDC_STC_QUERY_CONTROL           1150
#define IDC_CHK_EVENT_ALARM_IN          1151
#define IDC_CHK_EVENT_MOTION            1152
#define IDC_CHK_EVENT_OBJECT            1153
#define IDC_CHK_VLOSS                   1154
#define IDC_CHK_VANALYTICS              1155
#define IDC_SEARCH_EVENT_PRG_RATIO      1156
#define IDC_SEARCH_EVENT_BTN_STOP       1157
#define IDC_SEARCH_EVENT_STC_RATIO      1158
#define IDC_SEARCH_EVENT_STC_STRING     1159
#define IDC_STC_VIOLET_NAME             1160
#define IDC_EDT_VIOLET_STATUS           1161
#define IDC_STC_VIOLET_MODEL            1162
#define IDC_STC_VIOLET_KEY_PTZ_PRESET   1163
#define IDC_STC_VIOLET_KEY_PTZ_FOCUS    1164
#define IDC_STC_VIOLET_KEY_PTZ_IRIS     1165
#define IDC_STC_VIOLET_KEY_PTZ_AUTOPAN  1166
#define IDC_STC_VIOLET_KEY_PTZ_TOUR     1167
#define IDC_STC_VIOLET_KEY_PTZ_PATTERN  1168
#define IDC_STC_VIOLET_KEY_PTZ_HOME     1169
#define IDC_STC_VIOLET_KEY_PTZ_MENU     1170
#define IDC_STC_VIOLET_KEY_PTZ_LIGHT    1171
#define IDC_STC_VIOLET_KEY_PTZ_AUX      1172
#define IDC_STC_VIOLET_KEY_PTZ_ALARM    1173
#define IDC_STC_VIOLET_KEY_PTZ          1174
#define IDC_STC_VIOLET_KEY_ZOOM         1175
#define IDC_STC_VIOLET_KEY_DVR_PANIC    1176
#define IDC_STC_VIOLET_KEY_DVR_ALARM    1177
#define IDC_STC_VIOLET_KEY_DVR_DISP     1178
#define IDC_STC_VIOLET_KEY_DVR_GROUP    1179
#define IDC_STC_VIOLET_KEY_DVR_FREEZE   1180
#define IDC_STC_VIOLET_KEY_FULLSCREEN   1181
#define IDC_STC_VIOLET_KEY_DVR_PLAY     1182
#define IDC_STC_VIOLET_KEY_DVR_PLAY_RW  1183
#define IDC_STC_VIOLET_KEY_DVR_PLAY_NORMAL 1184
#define IDC_STC_VIOLET_KEY_DVR_PLAY_FF  1185
#define IDC_STC_VIOLET_KEY_DVR_MENU     1186
#define IDC_STC_VIOLET_KEY_DVR_RESERVED1 1187
#define IDC_STC_VIOLET_KEY_DVR_RESERVED2 1188
#define IDC_STC_VIOLET_KEY_DVR_RESERVED3 1189
#define IDC_BTN_VIOLET_CONNECT          1190
#define IDC_BTN_VIOLET_KEY_PTZ_TILT_UP  1191
#define IDC_BTN_VIOLET_KEY_PTZ_TILT_DOWN 1192
#define IDC_BTN_VIOLET_KEY_PTZ_PAN_LEFT 1193
#define IDC_BTN_VIOLET_KEY_PTZ_PAN_LEFT_UP 1194
#define IDC_BTN_VIOLET_KEY_PTZ_PAN_LEFT_DOWN 1195
#define IDC_BTN_VIOLET_KEY_PTZ_PAN_RIGHT 1196
#define IDC_BTN_VIOLET_KEY_PTZ_PAN_RIGHT_UP 1197
#define IDC_BTN_VIOLET_KEY_PTZ_PAN_RIGHT_DOWN 1198
#define IDC_BTN_VIOLET_KEY_PTZ_ZOOM_IN  1199
#define IDC_BTN_VIOLET_KEY_PTZ_ZOOM_OUT 1200
#define IDC_BTN_VIOLET_KEY_PTZ_SET_PRESET 1201
#define IDC_BTN_VIOLET_KEY_PTZ_VIEW_PRESET 1202
#define IDC_BTN_VIOLET_KEY_PTZ_FOCUS_IN 1203
#define IDC_BTN_VIOLET_KEY_PTZ_FOCUS_OUT 1204
#define IDC_BTN_VIOLET_KEY_PTZ_IRIS_OPEN 1205
#define IDC_BTN_VIOLET_KEY_PTZ_IRIS_CLOSE 1206
#define IDC_BTN_VIOLET_KEY_PTZ_AUTOPAN  1207
#define IDC_BTN_VIOLET_KEY_PTZ_TOUR     1208
#define IDC_BTN_VIOLET_KEY_PTZ_PATTERN  1209
#define IDC_BTN_VIOLET_KEY_PTZ_HOME     1210
#define IDC_BTN_VIOLET_KEY_PTZ_MENU     1211
#define IDC_BTN_VIOLET_KEY_PTZ_LIGHT    1212
#define IDC_BTN_VIOLET_KEY_PTZ_AUX      1213
#define IDC_BTN_VIOLET_KEY_PTZ_ALARM    1214
#define IDC_BTN_VIOLET_KEY_F1           1215
#define IDC_BTN_VIOLET_KEY_F2           1216
#define IDC_BTN_VIOLET_KEY_F3           1217
#define IDC_BTN_VIOLET_KEY_F4           1218
#define IDC_BTN_VIOLET_KEY_0            1219
#define IDC_BTN_VIOLET_KEY_1            1220
#define IDC_BTN_VIOLET_KEY_2            1221
#define IDC_BTN_VIOLET_KEY_3            1222
#define IDC_BTN_VIOLET_KEY_4            1223
#define IDC_BTN_VIOLET_KEY_5            1224
#define IDC_BTN_VIOLET_KEY_6            1225
#define IDC_BTN_VIOLET_KEY_7            1226
#define IDC_BTN_VIOLET_KEY_8            1227
#define IDC_BTN_VIOLET_KEY_9            1228
#define IDC_BTN_VIOLET_KEY_ESC          1229
#define IDC_BTN_VIOLET_KEY_PLUS         1230
#define IDC_BTN_VIOLET_KEY_MINUS        1231
#define IDC_BTN_VIOLET_KEY_DEV          1232
#define IDC_BTN_VIOLET_KEY_MON          1233
#define IDC_BTN_VIOLET_KEY_PANE         1234
#define IDC_BTN_VIOLET_KEY_CAM          1235
#define IDC_CHK_VIOLET_KEY_SHIFT        1236
#define IDC_BTN_VIOLET_KEY_MACRO        1237
#define IDC_BTN_VIOLET_KEY_ENTER        1238
#define IDC_BTN_VIOLET_KEY_DVR_PANIC    1239
#define IDC_BTN_VIOLET_KEY_DVR_ALARM    1240
#define IDC_BTN_VIOLET_KEY_DVR_DISP     1241
#define IDC_BTN_VIOLET_KEY_DVR_GROUP    1242
#define IDC_BTN_VIOLET_KEY_DVR_FREEZE   1243
#define IDC_BTN_VIOLET_KEY_FULLSCREEN   1244
#define IDC_BTN_VIOLET_KEY_DVR_PLAY     1245
#define IDC_BTN_VIOLET_KEY_DVR_PLAY_RW  1246
#define IDC_BTN_VIOLET_KEY_DVR_PLAY_NORMAL 1247
#define IDC_BTN_VIOLET_KEY_DVR_PLAY_FF  1248
#define IDC_BTN_VIOLET_KEY_DVR_MENU     1249
#define IDC_BTN_VIOLET_KEY_DVR_RESERVED1 1250
#define IDC_BTN_VIOLET_KEY_DVR_RESERVED2 1251
#define IDC_BTN_VIOLET_KEY_DVR_RESERVED3 1252
#define IDC_BTN_VIOLET_KEY_DVR_UP       1253
#define IDC_BTN_VIOLET_KEY_DVR_LEFT     1254
#define IDC_BTN_VIOLET_KEY_DVR_RIGHT    1255
#define IDC_BTN_VIOLET_KEY_DVR_DOWN     1256
#define IDC_BTN_VIOLET_SET_LAYOUT_MONITOR_LIVE 1257
#define IDC_EDT_VIOLET_LAYOUT_MON       1258
#define IDC_CBX_VIOLET_LAYOUT_LAYOUT    1259
#define IDC_EDT_VIOLET_MONITOR_MESSAGE  1260
#define IDC_EDT_VIOLET_MONITOR_NUMBER   1261
#define IDC_EDT_VIOLET_MESSAGE_TIMEOUT  1262
#define IDC_BTN_VIOLET_MESSAGE_SEND     1263
#define IDC_EDT_VIOLET_MESSAGE_FONT_SIZE 1264
#define IDC_CBX_VIOLET_MESSAGE_POSITION 1265
#define IDC_EDT_VIOLET_MONITOR_NUMBER_AUDIO 1266
#define IDC_EDT_VIOLET_DEVICE_ADDRESS   1267
#define IDC_EDT_VIOLET_DEVICE_PORT      1268
#define IDC_EDT_VIOLET_DEVICE_USER_ID   1269
#define IDC_EDT_VIOLET_DEVICE_USER_PW   1270
#define IDC_BTN_VIOLET_AUDIO_CONNECT    1271
#define IDC_BTN_VIOLET_AUDIO_DISCONNECT 1272
#define IDC_CHK_USE_VIOLET_FAILOVER_CONNECT 1273
#define IDC_EDT_VIOLET_LAYOUT_MONITOR   1274
#define IDC_CBX_VIOLET_LAYOUT_CAMERA    1275
#define IDC_CBX_VIOLET_LAYOUT_FORMAT    1276
#define IDC_BTN_VIOLET_LAYOUT_CHANGE    1277
#define IDC_BTN_BACKUP_CALENDAR         1278
#define IDC_EDT_VIOLET_NOTIFICATION     1278
#define IDC_BTN_BACKUP_GO_TO            1279
#define IDC_BTN_BACKUP_CLIPCOPY         1280
#define IDC_BTN_BACKUP_BACKWARD         1281
#define IDC_BTN_BACKUP_MOVE_STEP        1282
#define IDC_BTN_BACKUP_FORWARD          1283
#define IDC_BTN_BACKUP_STOP             1284
#define IDC_SLD_BACKUP_JOG_SHUTTLE      1285
#define IDC_CBX_BACKUP_SCREEN_FORMAT    1286
#define IDC_BTN_BACKUP_LAYOUT_PREV      1287
#define IDC_BTN_BACKUP_LAYOUT_NEXT      1288
#define IDC_BTN_BACKUP_PLAY             1289
#define IDC_STC_BACKUP_JOG_SPEED        1290
#define IDC_LST_SELECT_BACKUP_SITE      1291
#define IDC_BTN_SEARCH_G2_CALENDAR      1292
#define IDC_BTN_SEARCH_G2_GO_TO         1293
#define IDC_BTN_SEARCH_G2_CLIPCOPY      1294
#define IDC_BTN_SEARCH_G2_BACKWARD      1295
#define IDC_BTN_SEARCH_G2_MOVE_STEP     1296
#define IDC_BTN_SEARCH_G2_FORWARD       1297
#define IDC_BTN_SEARCH_G2_STOP          1298
#define IDC_SLD_SEARCH_G2_SPEED         1299
#define IDC_STC_SEARCH_G2_SPEED         1300
#define IDC_CBX_SEARCH_G2_SCREEN_FORMAT 1301
#define IDC_BTN_SEARCH_G2_LAYOUT_PREV   1302
#define IDC_BTN_SEARCH_G2_LAYOUT_NEXT   1303
#define IDC_BTN_SEARCH_G2_PLAY          1304
#define IDC_LST_SELECT_SEARCH_G2_SITE   1305
#define IDC_BTN_SEARCH_G2_MODE          1306
#define IDC_BTN_SEARCH_G2_FILTER        1307
#define IDC_RDO_VIOLET_MONITOR_MESSAGE_SHOW 1308
#define IDC_RDO_VIOLET_MONITOR_MESSAGE_HIDE 1309
#define IDC_BTN_BACKUP_MODE             1310
#define IDC_BTN_BACKUP_FILTER           1311
#define IDC_DEVICE_INFO_STC_TEXT        1312
#define IDC_DEVICE_INFO_EDT_SITE        1313
#define IDC_DEVICE_INFO_EDT_ADDRESS     1314
#define IDC_DEVICE_INFO_EDT_PORT_ADMIN  1315
#define IDC_DEVICE_INFO_EDT_PORT_WATCH  1316
#define IDC_DEVICE_INFO_EDT_PORT_SEARCH 1317
#define IDC_DEVICE_INFO_EDT_PORT_AUDIO  1318
#define IDC_DEVICE_INFO_EDT_ID          1319
#define IDC_DEVICE_INFO_EDT_PASSWORD    1320
#define IDC_STC_COLOR_EFFECT            1321
#define IDC_CBX_COLOR_EFFECT_CMD        1322
#define IDC_BTN_COLOR_EFFECT_UP         1323
#define IDC_BTN_COLOR_EFFECT_DOWN       1324
#define IDC_STC_ALARMOUT                1325
#define IDC_CBX_ALARMOUT                1326
#define IDC_BTN_ALARMOUT_ON             1327
#define IDC_BTN_ALARMOUT_OFF            1328
#define IDC_STATUS_EDT                  1329
#define IDC_STATUS_BTN_UPDATE_STATUS    1330
#define IDC_STATUS_STC_SITE             1331
#define ID_MAIN_SYSTEM_LOGIN            33000
#define ID_MAIN_SYSTEM_LOGOUT           33001
#define ID_SCREEN_CONNECT_WATCH         33002
#define ID_SCREEN_CONNECT_SEARCH        33003
#define ID_CAMERA_REMOVE_CAMERA         33004
#define ID_CAMERA_REMOVE_DEVICE         33005
#define ID_REMOVE_ALLCAMERAS            33006
#define ID_CAMERA_REMOVE_ALL            33007
#define ID_CAMERA_RATIO_FIT_TO_SCREEN   33008
#define ID_CAMERA_RATIO_ORIGINAL        33009
#define ID_PLAY_GOTO_FIRST              33010
#define ID_PLAY_GOTO_LAST               33011
#define ID_PLAY_GOTO_TIME               33012
#define ID_PLAY_MOVE_1FRAME             33013
#define ID_PLAY_MOVE_1MINUTE            33014
#define ID_PLAY_MOVE_5MINUTE            33015
#define ID_PLAY_MOVE_10MINUTE           33016
#define ID_PLAY_MOVE_15MINUTE           33017
#define ID_PLAY_MOVE_30MINUTE           33018
#define ID_PLAY_MOVE_60MINUTE           33019
#define ID_VIEW_LIVE                    33020
#define ID_VIEW_LOG                     33021
#define ID_MAIN_VIEW_SCREEN             33022
#define ID_MAIN_VIEW_LOG                33023
#define ID_CAMERA_PANICRECORDING        33024
#define ID_CAMERA_INSTANT_RECORD        33025
#define ID_ADDITIONAL_DATASOURCE        33026
#define ID_ADDITIONAL_SELECTSEGMENT     33027
#define ID_DATASOURCE_SEARCHONLOCAL     33028
#define ID_DATASOURCE_SEARCHONARCHIVE   33029
#define ID_DATASOURCE_SEARCHONOTHER     33030
#define ID_SEARCH_ADDITIONAL_SELECTSEGMENT 33031
#define ID_VIOLET_INK                   33032
#define ID_CAMERA_LISTEN                33034
#define ID_CAMERA_TALK                  33035
#define ID_SCREEN_CONNECT_BACKUP        33036
#define ID_SEARCH_G2_GOTO_FIRST         33047
#define ID_SEARCH_G2_GOTO_LAST          33048
#define ID_SEARCH_G2_GOTO_TIME          33049
#define ID_SEARCH_G2_MOVE_1FRAME        33050
#define ID_SEARCH_G2_MOVE_1MINUTE       33051
#define ID_SEARCH_G2_MOVE_5MINUTE       33052
#define ID_SEARCH_G2_MOVE_10MINUTE      33053
#define ID_SEARCH_G2_MOVE_15MINUTE      33054
#define ID_SEARCH_G2_MOVE_30MINUTE      33055
#define ID_SEARCH_G2_MOVE_60MINUTE      33056
#define ID_MAIN_SYSTEM_ADD              33057
#define ID_MAIN_SYSTEM_REMOVE           33058
#define ID_MAIN_SYSTEM_MODIFY           33059
#define ID_MAIN_SYSTEM_STATUS           33060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         33062
#define _APS_NEXT_CONTROL_VALUE         1333
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
