<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <UnityWSASolutionName>PrototypeTest</UnityWSASolutionName>
        <UnityWSASolutionDir>D:\HololensBuild\PrototypeTest\</UnityWSASolutionDir>
        <UnityProjectDir>D:\HololensTest\PrototypeTest\</UnityProjectDir>
        <UnityWSAPlayerDir>D:\2017_LTS_Unity\Editor\Data\PlaybackEngines\MetroSupport\</UnityWSAPlayerDir>
        <UnityWSAToolsDir>$(UnityWSASolutionDir)Unity\Tools\</UnityWSAToolsDir>
    </PropertyGroup>
</Project>
