<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Configurations>Debug;Release;Release_UNE_MCS;Release_SKT_MCS;Release_Kakao;Release_Soulbrain_MCS;Release_Kakaowork</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Kakao|AnyCPU'">
    <DefineConstants>TRACE;Kakao</DefineConstants>
    <Optimize>false</Optimize>
    <OutputPath>D:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Kakaowork|AnyCPU'">
    <DefineConstants>TRACE;Kakaowork</DefineConstants>
    <Optimize>false</Optimize>
    <OutputPath>D:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_UNE_MCS|AnyCPU'">
    <DefineConstants>TRACE;UNE_MCS</DefineConstants>
    <OutputPath>D:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_SKT_MCS|AnyCPU'">
    <DefineConstants>TRACE;SKT_MCS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Soulbrain_MCS|AnyCPU'">
    <DefineConstants>TRACE;Soulbrain_MCS</DefineConstants>
    <OutputPath>D:\UnESolution\bin\common12\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;Kakaowork</DefineConstants>
    <OutputPath>..\..\..\..\..\bin\common12</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.DAL\Common.DAL.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.IDAL\Common.IDAL.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Model\Common.Model.csproj" />
    <ProjectReference Include="..\..\..\SDMS\SDMS.DAL\SDMS.DAL.csproj" />
    <ProjectReference Include="..\..\..\SDMS\SDMS.IDAL\SDMS.IDAL.csproj" />
    <ProjectReference Include="..\..\..\SDMS\SDMS.Model\SDMS.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="dnsData">
      <HintPath>..\..\dnsData\bin\Debug\netstandard2.0\dnsData.dll</HintPath>
    </Reference>
    <Reference Include="dnsDBUtil">
      <HintPath>..\..\..\..\..\bin\common12\netstandard2.0\dnsDBUtil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
