//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenarioServiceTester.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://unes.iptime.org/presafe", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://unes.iptime.org/presafe", ConfigurationName="ServiceReference1.PreSafeSoap")]
    public interface PreSafeSoap {
        
        // CODEGEN: http://unes.iptime.org/presafe 네임스페이스의 요소 이름 SenarioListResult이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://unes.iptime.org/presafe/SenarioList", ReplyAction="*")]
        SenarioServiceTester.ServiceReference1.SenarioListResponse SenarioList(SenarioServiceTester.ServiceReference1.SenarioListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unes.iptime.org/presafe/SenarioList", ReplyAction="*")]
        System.Threading.Tasks.Task<SenarioServiceTester.ServiceReference1.SenarioListResponse> SenarioListAsync(SenarioServiceTester.ServiceReference1.SenarioListRequest request);
        
        // CODEGEN: http://unes.iptime.org/presafe 네임스페이스의 요소 이름 senarioName이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://unes.iptime.org/presafe/RunSenario", ReplyAction="*")]
        SenarioServiceTester.ServiceReference1.RunSenarioResponse RunSenario(SenarioServiceTester.ServiceReference1.RunSenarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unes.iptime.org/presafe/RunSenario", ReplyAction="*")]
        System.Threading.Tasks.Task<SenarioServiceTester.ServiceReference1.RunSenarioResponse> RunSenarioAsync(SenarioServiceTester.ServiceReference1.RunSenarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SenarioListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SenarioList", Namespace="http://unes.iptime.org/presafe", Order=0)]
        public SenarioServiceTester.ServiceReference1.SenarioListRequestBody Body;
        
        public SenarioListRequest() {
        }
        
        public SenarioListRequest(SenarioServiceTester.ServiceReference1.SenarioListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SenarioListRequestBody {
        
        public SenarioListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SenarioListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SenarioListResponse", Namespace="http://unes.iptime.org/presafe", Order=0)]
        public SenarioServiceTester.ServiceReference1.SenarioListResponseBody Body;
        
        public SenarioListResponse() {
        }
        
        public SenarioListResponse(SenarioServiceTester.ServiceReference1.SenarioListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://unes.iptime.org/presafe")]
    public partial class SenarioListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SenarioServiceTester.ServiceReference1.ArrayOfString SenarioListResult;
        
        public SenarioListResponseBody() {
        }
        
        public SenarioListResponseBody(SenarioServiceTester.ServiceReference1.ArrayOfString SenarioListResult) {
            this.SenarioListResult = SenarioListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunSenarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunSenario", Namespace="http://unes.iptime.org/presafe", Order=0)]
        public SenarioServiceTester.ServiceReference1.RunSenarioRequestBody Body;
        
        public RunSenarioRequest() {
        }
        
        public RunSenarioRequest(SenarioServiceTester.ServiceReference1.RunSenarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://unes.iptime.org/presafe")]
    public partial class RunSenarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senarioName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool bUseSound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float nSoundLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool bUseHeartBeat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nHeartBeat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool bUseAlcole;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public float nAlcole;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool bUseVelocity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public float nVelocity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool bUseAcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public float nAccelate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool bUseLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int nLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool bUseImpact;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool bImpact;
        
        public RunSenarioRequestBody() {
        }
        
        public RunSenarioRequestBody(string senarioName, bool bUseSound, float nSoundLevel, bool bUseHeartBeat, int nHeartBeat, bool bUseAlcole, float nAlcole, bool bUseVelocity, float nVelocity, bool bUseAcc, float nAccelate, bool bUseLocation, int nLocation, bool bUseImpact, bool bImpact) {
            this.senarioName = senarioName;
            this.bUseSound = bUseSound;
            this.nSoundLevel = nSoundLevel;
            this.bUseHeartBeat = bUseHeartBeat;
            this.nHeartBeat = nHeartBeat;
            this.bUseAlcole = bUseAlcole;
            this.nAlcole = nAlcole;
            this.bUseVelocity = bUseVelocity;
            this.nVelocity = nVelocity;
            this.bUseAcc = bUseAcc;
            this.nAccelate = nAccelate;
            this.bUseLocation = bUseLocation;
            this.nLocation = nLocation;
            this.bUseImpact = bUseImpact;
            this.bImpact = bImpact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunSenarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunSenarioResponse", Namespace="http://unes.iptime.org/presafe", Order=0)]
        public SenarioServiceTester.ServiceReference1.RunSenarioResponseBody Body;
        
        public RunSenarioResponse() {
        }
        
        public RunSenarioResponse(SenarioServiceTester.ServiceReference1.RunSenarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://unes.iptime.org/presafe")]
    public partial class RunSenarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SenarioServiceTester.ServiceReference1.ArrayOfString RunSenarioResult;
        
        public RunSenarioResponseBody() {
        }
        
        public RunSenarioResponseBody(SenarioServiceTester.ServiceReference1.ArrayOfString RunSenarioResult) {
            this.RunSenarioResult = RunSenarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PreSafeSoapChannel : SenarioServiceTester.ServiceReference1.PreSafeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreSafeSoapClient : System.ServiceModel.ClientBase<SenarioServiceTester.ServiceReference1.PreSafeSoap>, SenarioServiceTester.ServiceReference1.PreSafeSoap {
        
        public PreSafeSoapClient() {
        }
        
        public PreSafeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreSafeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreSafeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreSafeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SenarioServiceTester.ServiceReference1.SenarioListResponse SenarioServiceTester.ServiceReference1.PreSafeSoap.SenarioList(SenarioServiceTester.ServiceReference1.SenarioListRequest request) {
            return base.Channel.SenarioList(request);
        }
        
        public SenarioServiceTester.ServiceReference1.ArrayOfString SenarioList() {
            SenarioServiceTester.ServiceReference1.SenarioListRequest inValue = new SenarioServiceTester.ServiceReference1.SenarioListRequest();
            inValue.Body = new SenarioServiceTester.ServiceReference1.SenarioListRequestBody();
            SenarioServiceTester.ServiceReference1.SenarioListResponse retVal = ((SenarioServiceTester.ServiceReference1.PreSafeSoap)(this)).SenarioList(inValue);
            return retVal.Body.SenarioListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SenarioServiceTester.ServiceReference1.SenarioListResponse> SenarioServiceTester.ServiceReference1.PreSafeSoap.SenarioListAsync(SenarioServiceTester.ServiceReference1.SenarioListRequest request) {
            return base.Channel.SenarioListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SenarioServiceTester.ServiceReference1.SenarioListResponse> SenarioListAsync() {
            SenarioServiceTester.ServiceReference1.SenarioListRequest inValue = new SenarioServiceTester.ServiceReference1.SenarioListRequest();
            inValue.Body = new SenarioServiceTester.ServiceReference1.SenarioListRequestBody();
            return ((SenarioServiceTester.ServiceReference1.PreSafeSoap)(this)).SenarioListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SenarioServiceTester.ServiceReference1.RunSenarioResponse SenarioServiceTester.ServiceReference1.PreSafeSoap.RunSenario(SenarioServiceTester.ServiceReference1.RunSenarioRequest request) {
            return base.Channel.RunSenario(request);
        }
        
        public SenarioServiceTester.ServiceReference1.ArrayOfString RunSenario(string senarioName, bool bUseSound, float nSoundLevel, bool bUseHeartBeat, int nHeartBeat, bool bUseAlcole, float nAlcole, bool bUseVelocity, float nVelocity, bool bUseAcc, float nAccelate, bool bUseLocation, int nLocation, bool bUseImpact, bool bImpact) {
            SenarioServiceTester.ServiceReference1.RunSenarioRequest inValue = new SenarioServiceTester.ServiceReference1.RunSenarioRequest();
            inValue.Body = new SenarioServiceTester.ServiceReference1.RunSenarioRequestBody();
            inValue.Body.senarioName = senarioName;
            inValue.Body.bUseSound = bUseSound;
            inValue.Body.nSoundLevel = nSoundLevel;
            inValue.Body.bUseHeartBeat = bUseHeartBeat;
            inValue.Body.nHeartBeat = nHeartBeat;
            inValue.Body.bUseAlcole = bUseAlcole;
            inValue.Body.nAlcole = nAlcole;
            inValue.Body.bUseVelocity = bUseVelocity;
            inValue.Body.nVelocity = nVelocity;
            inValue.Body.bUseAcc = bUseAcc;
            inValue.Body.nAccelate = nAccelate;
            inValue.Body.bUseLocation = bUseLocation;
            inValue.Body.nLocation = nLocation;
            inValue.Body.bUseImpact = bUseImpact;
            inValue.Body.bImpact = bImpact;
            SenarioServiceTester.ServiceReference1.RunSenarioResponse retVal = ((SenarioServiceTester.ServiceReference1.PreSafeSoap)(this)).RunSenario(inValue);
            return retVal.Body.RunSenarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SenarioServiceTester.ServiceReference1.RunSenarioResponse> SenarioServiceTester.ServiceReference1.PreSafeSoap.RunSenarioAsync(SenarioServiceTester.ServiceReference1.RunSenarioRequest request) {
            return base.Channel.RunSenarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SenarioServiceTester.ServiceReference1.RunSenarioResponse> RunSenarioAsync(string senarioName, bool bUseSound, float nSoundLevel, bool bUseHeartBeat, int nHeartBeat, bool bUseAlcole, float nAlcole, bool bUseVelocity, float nVelocity, bool bUseAcc, float nAccelate, bool bUseLocation, int nLocation, bool bUseImpact, bool bImpact) {
            SenarioServiceTester.ServiceReference1.RunSenarioRequest inValue = new SenarioServiceTester.ServiceReference1.RunSenarioRequest();
            inValue.Body = new SenarioServiceTester.ServiceReference1.RunSenarioRequestBody();
            inValue.Body.senarioName = senarioName;
            inValue.Body.bUseSound = bUseSound;
            inValue.Body.nSoundLevel = nSoundLevel;
            inValue.Body.bUseHeartBeat = bUseHeartBeat;
            inValue.Body.nHeartBeat = nHeartBeat;
            inValue.Body.bUseAlcole = bUseAlcole;
            inValue.Body.nAlcole = nAlcole;
            inValue.Body.bUseVelocity = bUseVelocity;
            inValue.Body.nVelocity = nVelocity;
            inValue.Body.bUseAcc = bUseAcc;
            inValue.Body.nAccelate = nAccelate;
            inValue.Body.bUseLocation = bUseLocation;
            inValue.Body.nLocation = nLocation;
            inValue.Body.bUseImpact = bUseImpact;
            inValue.Body.bImpact = bImpact;
            return ((SenarioServiceTester.ServiceReference1.PreSafeSoap)(this)).RunSenarioAsync(inValue);
        }
    }
}
