//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUtility2.WebDBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebDBService.IWebDB")]
    public interface IWebDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/RunQuery", ReplyAction="http://tempuri.org/IWebDB/RunQueryResponse")]
        string[] RunQuery(string dbName, string dbType, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/RunQuery", ReplyAction="http://tempuri.org/IWebDB/RunQueryResponse")]
        System.Threading.Tasks.Task<string[]> RunQueryAsync(string dbName, string dbType, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BeginBatch", ReplyAction="http://tempuri.org/IWebDB/BeginBatchResponse")]
        DBUtility2.WebDBService.BeginBatchResponse BeginBatch(DBUtility2.WebDBService.BeginBatchRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BeginBatch", ReplyAction="http://tempuri.org/IWebDB/BeginBatchResponse")]
        System.Threading.Tasks.Task<DBUtility2.WebDBService.BeginBatchResponse> BeginBatchAsync(DBUtility2.WebDBService.BeginBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchCommmit", ReplyAction="http://tempuri.org/IWebDB/BatchCommmitResponse")]
        string BatchCommmit(long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchCommmit", ReplyAction="http://tempuri.org/IWebDB/BatchCommmitResponse")]
        System.Threading.Tasks.Task<string> BatchCommmitAsync(long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchRollback", ReplyAction="http://tempuri.org/IWebDB/BatchRollbackResponse")]
        string BatchRollback(long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchRollback", ReplyAction="http://tempuri.org/IWebDB/BatchRollbackResponse")]
        System.Threading.Tasks.Task<string> BatchRollbackAsync(long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchQuery", ReplyAction="http://tempuri.org/IWebDB/BatchQueryResponse")]
        string[] BatchQuery(string query, long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchQuery", ReplyAction="http://tempuri.org/IWebDB/BatchQueryResponse")]
        System.Threading.Tasks.Task<string[]> BatchQueryAsync(string query, long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BeginMultiQuery", ReplyAction="http://tempuri.org/IWebDB/BeginMultiQueryResponse")]
        long BeginMultiQuery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BeginMultiQuery", ReplyAction="http://tempuri.org/IWebDB/BeginMultiQueryResponse")]
        System.Threading.Tasks.Task<long> BeginMultiQueryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/AddMultiQuery", ReplyAction="http://tempuri.org/IWebDB/AddMultiQueryResponse")]
        string AddMultiQuery(string strSQL, long key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/AddMultiQuery", ReplyAction="http://tempuri.org/IWebDB/AddMultiQueryResponse")]
        System.Threading.Tasks.Task<string> AddMultiQueryAsync(string strSQL, long key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/RunMultiQuery", ReplyAction="http://tempuri.org/IWebDB/RunMultiQueryResponse")]
        string[] RunMultiQuery(string dbName, string dbType, long key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/RunMultiQuery", ReplyAction="http://tempuri.org/IWebDB/RunMultiQueryResponse")]
        System.Threading.Tasks.Task<string[]> RunMultiQueryAsync(string dbName, string dbType, long key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchMultiQuery", ReplyAction="http://tempuri.org/IWebDB/BatchMultiQueryResponse")]
        string[] BatchMultiQuery(long key, long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/BatchMultiQuery", ReplyAction="http://tempuri.org/IWebDB/BatchMultiQueryResponse")]
        System.Threading.Tasks.Task<string[]> BatchMultiQueryAsync(long key, long transactionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/CancelMultiQuery", ReplyAction="http://tempuri.org/IWebDB/CancelMultiQueryResponse")]
        string CancelMultiQuery(long key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebDB/CancelMultiQuery", ReplyAction="http://tempuri.org/IWebDB/CancelMultiQueryResponse")]
        System.Threading.Tasks.Task<string> CancelMultiQueryAsync(long key);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginBatch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BeginBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dbName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dbType;
        
        public BeginBatchRequest() {
        }
        
        public BeginBatchRequest(string dbName, string dbType) {
            this.dbName = dbName;
            this.dbType = dbType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginBatchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BeginBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long BeginBatchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public BeginBatchResponse() {
        }
        
        public BeginBatchResponse(long BeginBatchResult, string errorMessage) {
            this.BeginBatchResult = BeginBatchResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebDBChannel : DBUtility2.WebDBService.IWebDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebDBClient : System.ServiceModel.ClientBase<DBUtility2.WebDBService.IWebDB>, DBUtility2.WebDBService.IWebDB {
        
        public WebDBClient() {
        }
        
        public WebDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] RunQuery(string dbName, string dbType, string query) {
            return base.Channel.RunQuery(dbName, dbType, query);
        }
        
        public System.Threading.Tasks.Task<string[]> RunQueryAsync(string dbName, string dbType, string query) {
            return base.Channel.RunQueryAsync(dbName, dbType, query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBUtility2.WebDBService.BeginBatchResponse DBUtility2.WebDBService.IWebDB.BeginBatch(DBUtility2.WebDBService.BeginBatchRequest request) {
            return base.Channel.BeginBatch(request);
        }
        
        public long BeginBatch(string dbName, string dbType, out string errorMessage) {
            DBUtility2.WebDBService.BeginBatchRequest inValue = new DBUtility2.WebDBService.BeginBatchRequest();
            inValue.dbName = dbName;
            inValue.dbType = dbType;
            DBUtility2.WebDBService.BeginBatchResponse retVal = ((DBUtility2.WebDBService.IWebDB)(this)).BeginBatch(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.BeginBatchResult;
        }
        
        public System.Threading.Tasks.Task<DBUtility2.WebDBService.BeginBatchResponse> BeginBatchAsync(DBUtility2.WebDBService.BeginBatchRequest request) {
            return base.Channel.BeginBatchAsync(request);
        }
        
        public string BatchCommmit(long transactionKey) {
            return base.Channel.BatchCommmit(transactionKey);
        }
        
        public System.Threading.Tasks.Task<string> BatchCommmitAsync(long transactionKey) {
            return base.Channel.BatchCommmitAsync(transactionKey);
        }
        
        public string BatchRollback(long transactionKey) {
            return base.Channel.BatchRollback(transactionKey);
        }
        
        public System.Threading.Tasks.Task<string> BatchRollbackAsync(long transactionKey) {
            return base.Channel.BatchRollbackAsync(transactionKey);
        }
        
        public string[] BatchQuery(string query, long transactionKey) {
            return base.Channel.BatchQuery(query, transactionKey);
        }
        
        public System.Threading.Tasks.Task<string[]> BatchQueryAsync(string query, long transactionKey) {
            return base.Channel.BatchQueryAsync(query, transactionKey);
        }
        
        public long BeginMultiQuery() {
            return base.Channel.BeginMultiQuery();
        }
        
        public System.Threading.Tasks.Task<long> BeginMultiQueryAsync() {
            return base.Channel.BeginMultiQueryAsync();
        }
        
        public string AddMultiQuery(string strSQL, long key) {
            return base.Channel.AddMultiQuery(strSQL, key);
        }
        
        public System.Threading.Tasks.Task<string> AddMultiQueryAsync(string strSQL, long key) {
            return base.Channel.AddMultiQueryAsync(strSQL, key);
        }
        
        public string[] RunMultiQuery(string dbName, string dbType, long key) {
            return base.Channel.RunMultiQuery(dbName, dbType, key);
        }
        
        public System.Threading.Tasks.Task<string[]> RunMultiQueryAsync(string dbName, string dbType, long key) {
            return base.Channel.RunMultiQueryAsync(dbName, dbType, key);
        }
        
        public string[] BatchMultiQuery(long key, long transactionKey) {
            return base.Channel.BatchMultiQuery(key, transactionKey);
        }
        
        public System.Threading.Tasks.Task<string[]> BatchMultiQueryAsync(long key, long transactionKey) {
            return base.Channel.BatchMultiQueryAsync(key, transactionKey);
        }
        
        public string CancelMultiQuery(long key) {
            return base.Channel.CancelMultiQuery(key);
        }
        
        public System.Threading.Tasks.Task<string> CancelMultiQueryAsync(long key) {
            return base.Channel.CancelMultiQueryAsync(key);
        }
    }
}
