<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <SccProjectName />
    <SccLocalPath />
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseOfMfc>false</UseOfMfc>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseOfMfc>false</UseOfMfc>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseOfMfc>false</UseOfMfc>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseOfMfc>false</UseOfMfc>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(VCTargetsPath)Microsoft.Cpp.UpgradeFromVC60.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(VCTargetsPath)Microsoft.Cpp.UpgradeFromVC60.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(VCTargetsPath)Microsoft.Cpp.UpgradeFromVC60.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(VCTargetsPath)Microsoft.Cpp.UpgradeFromVC60.props" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <LinkIncremental>true</LinkIncremental>
    <TargetName>$(ProjectName)D</TargetName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <LinkIncremental>true</LinkIncremental>
    <TargetName>$(ProjectName)D</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <InlineFunctionExpansion>OnlyExplicitInline</InlineFunctionExpansion>
      <StringPooling>true</StringPooling>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <Optimization>MaxSpeed</Optimization>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <WarningLevel>Level3</WarningLevel>
      <AdditionalIncludeDirectories>..\..\..\include\OpenAL;..\..\..\include\OpenAL\OpenAL32;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>NDEBUG;_WINDOWS;_USRDLL;ALUT_EXPORTS;WIN32;ALUT_BUILD_LIBRARY;HAVE__STAT;HAVE___INT8;HAVE_SLEEP;HAVE_WINDOWS_H;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Midl>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <TypeLibraryName>.\Release\alut.tlb</TypeLibraryName>
      <MkTypLibCompatible>true</MkTypLibCompatible>
      <TargetEnvironment>Win32</TargetEnvironment>
    </Midl>
    <ResourceCompile>
      <Culture>0x0407</Culture>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Bscmake>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <OutputFile>.\Release\alut.bsc</OutputFile>
    </Bscmake>
    <Link>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <LinkDLL>true</LinkDLL>
      <SubSystem>Console</SubSystem>
      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib\OpenAL32</AdditionalLibraryDirectories>
      <AdditionalDependencies>odbc32.lib;odbccp32.lib;openal32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <StripPrivateSymbols>$(TargetDir)$(TargetName)2.pdb</StripPrivateSymbols>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <InlineFunctionExpansion>OnlyExplicitInline</InlineFunctionExpansion>
      <StringPooling>true</StringPooling>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <Optimization>MaxSpeed</Optimization>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <WarningLevel>Level3</WarningLevel>
      <AdditionalIncludeDirectories>$(UNE_HOME)\esdk\include\OpenAL;$(UNE_HOME)\esdk\include\OpenAL\OpenAL32;$(UNE_HOME)\esdk\include\OpenAL32;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>NDEBUG;_WINDOWS;_USRDLL;ALUT_EXPORTS;WIN32;ALUT_BUILD_LIBRARY;HAVE__STAT;HAVE___INT8;HAVE_SLEEP;HAVE_WINDOWS_H;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Midl>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <TypeLibraryName>.\Release\alut.tlb</TypeLibraryName>
      <MkTypLibCompatible>true</MkTypLibCompatible>
    </Midl>
    <ResourceCompile>
      <Culture>0x0407</Culture>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Bscmake>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <OutputFile>.\Release\alut.bsc</OutputFile>
    </Bscmake>
    <Link>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <LinkDLL>true</LinkDLL>
      <SubSystem>Console</SubSystem>
      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib64;$(UNE_HOME)\esdk\lib64\OpenAL32;$(DXSDK_DIR)\lib\x64</AdditionalLibraryDirectories>
      <AdditionalDependencies>odbc32.lib;odbccp32.lib;openal32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <StripPrivateSymbols>$(TargetDir)$(TargetName)2.pdb</StripPrivateSymbols>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
    <ProjectReference>
      <LinkLibraryDependencies>false</LinkLibraryDependencies>
    </ProjectReference>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <InlineFunctionExpansion>Default</InlineFunctionExpansion>
      <FunctionLevelLinking>false</FunctionLevelLinking>
      <Optimization>Disabled</Optimization>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <WarningLevel>Level3</WarningLevel>
      <MinimalRebuild>true</MinimalRebuild>
      <DebugInformationFormat>EditAndContinue</DebugInformationFormat>
      <AdditionalIncludeDirectories>..\..\..\include\OpenAL\OpenAL32;..\..\..\include\OpenAL;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_DEBUG;_WINDOWS;_USRDLL;ALUT_EXPORTS;WIN32;ALUT_BUILD_LIBRARY;HAVE__STAT;HAVE___INT8;HAVE_SLEEP;HAVE_WINDOWS_H;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
    </ClCompile>
    <Midl>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <TypeLibraryName>.\Debug\alut.tlb</TypeLibraryName>
      <MkTypLibCompatible>true</MkTypLibCompatible>
      <TargetEnvironment>Win32</TargetEnvironment>
    </Midl>
    <ResourceCompile>
      <Culture>0x0407</Culture>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Bscmake>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <OutputFile>.\Debug\alut.bsc</OutputFile>
    </Bscmake>
    <Link>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <LinkDLL>true</LinkDLL>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Console</SubSystem>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib\OpenAL32</AdditionalLibraryDirectories>
      <AdditionalDependencies>odbc32.lib;odbccp32.lib;openal32d.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <InlineFunctionExpansion>Default</InlineFunctionExpansion>
      <FunctionLevelLinking>false</FunctionLevelLinking>
      <Optimization>Disabled</Optimization>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <AdditionalIncludeDirectories>$(UNE_HOME)\esdk\include\OpenAL;$(UNE_HOME)\esdk\include\OpenAL\OpenAL32;$(UNE_HOME)\esdk\include\OpenAL32;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_DEBUG;_WINDOWS;_USRDLL;ALUT_EXPORTS;WIN32;ALUT_BUILD_LIBRARY;HAVE__STAT;HAVE___INT8;HAVE_SLEEP;HAVE_WINDOWS_H;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
    </ClCompile>
    <Midl>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <TypeLibraryName>.\Debug\alut.tlb</TypeLibraryName>
      <MkTypLibCompatible>true</MkTypLibCompatible>
    </Midl>
    <ResourceCompile>
      <Culture>0x0407</Culture>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Bscmake>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <OutputFile>.\Debug\alut.bsc</OutputFile>
    </Bscmake>
    <Link>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <LinkDLL>true</LinkDLL>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Console</SubSystem>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib64\OpenAL32</AdditionalLibraryDirectories>
      <AdditionalDependencies>odbc32.lib;odbccp32.lib;openal32d.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\OpenAL32\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutBufferData.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutCodec.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutError.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutInit.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutInputStream.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutLoader.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutOutputStream.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutUtil.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutVersion.c" />
    <ClCompile Include="..\..\..\src\OpenAL\ALUT\alutWaveform.c" />
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="..\..\..\src\OpenAL\ALUT\alutInternal.h" />
    <ClInclude Include="..\..\..\include\OpenAL\AL\alut.h" />
    <ClInclude Include="..\..\..\src\OpenAL\ALUT\resource.h" />
  </ItemGroup>
  <ItemGroup>
    <ResourceCompile Include="..\..\..\src\OpenAL\ALUT\alut.rc" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>