[Server Connection Info]
# 사이트 번호 KPX 500
siteid=500
# FTP Logger Backup 사용여부 1이면 사용
loggerbackup=0
duration=604800
# 시간동기화 주기 : 1주일
timesync=604800 
alarm=0

[Jubix Logger]
ipaddr=195.1.1.81
#ipaddr=127.0.0.1
port=33333
interval=1000

[Paragon]
# Paragon 에서 배관 압력값을 가져오기 위한 통신 (PT-4101, PT4102)
ipaddr=195.1.1.88
port=502
interval=1000