//=============================================================
//
// C4 Engine version 2.9.1
// Copyright 1999-2012, by Terathon Software LLC
//
// This copy is licensed to the following:
//
//     Registered user: Soo Ki Kim
//     Maximum number of users: 1
//     License #C4T0035002
//
// License is granted under terms of the license agreement
// entered by the registed user.
//
// Unauthorized redistribution of source code is strictly
// prohibited. Violators will be prosecuted.
//
//=============================================================


#ifndef C4Sources_h
#define C4Sources_h


//# \component	World Manager
//# \prefix		WorldMgr/


#include "C4Objects.h"
#include "C4Regions.h"
#include "C4Sound.h"
#include "C4Time.h"


namespace C4
{
	typedef Type	SourceType;
	
	
	enum
	{
		kObjectSource		= 'SORC'
	};
	
	
	//# \enum	SourceType
	
	enum
	{
		kSourceAmbient		= 'AMBT',		//## Ambient sound source.
		kSourceOmni			= 'OMNI',		//## Omnidirectional sound source.
		kSourceDirected		= 'DRCT'		//## Directed sound source.
	};
	
	
	//# \enum	SourceFlags
	
	enum
	{
		kSourceRandom			= 1 << 0,	//## The source starts playing at a random position when it becomes audible. (Ignored if the $kSourceStream$ flag is set or if the $kSourceLoop$ flag is not set.)
		kSourceStream			= 1 << 1,	//## The source is streamed from disk.
		kSourceInitialPlay		= 1 << 2,	//## The source is initially playing.
		kSourceLoop				= 1 << 3,	//## The source is looping.
		kSourceDopplerShift		= 1 << 4,	//## The Doppler effect is applied to the source.
		kSourceDistanceDelay	= 1 << 5,	//## Distance delay is applied to the source.
		kSourceReverb			= 1 << 6,	//## Reflections and reverberation are generated by the source.
		kSourceObstruction		= 1 << 7,	//## The source can be obstructed by geometry.
		kSourceExternalZone		= 1 << 8	//## The source's position may temporarily be outside its owning zone.
	};
	
	
	enum
	{
		kSourcePersistent		= 1 << 0,
		kSourcePlaying			= 1 << 1,
		kSourceStopped			= 1 << 2,
		kSourceInitialized		= 1 << 7,
		kSourceEngaged			= 1 << 8,
		kSourceAudible			= 1 << 9
	};
	
	
	class ZoneRegion;
	class SourceRegion;
	
	
	class SoundData : public ListElement<SoundData>
	{
		private:
			
			ResourceName	soundName;
		
		public:
			
			C4API SoundData(const char *name);
			C4API ~SoundData();
			
			const ResourceName& GetSoundName(void) const
			{
				return (soundName);
			}
			
			void SetSoundName(const char *name)
			{
				soundName = name;
			}
	};
	
	
	//# \class	SourceObject	Encapsulates data pertaining to a sound source.
	//
	//# The $SourceObject$ class encapsulates data pertaining to a sound source.
	//
	//# \def	class SourceObject : public Object
	//
	//# \ctor	SourceObject(SourceType type, const char *name);
	//
	//# The constructor has protected access. The $SourceObject$ class can only exist as the base class for another class.
	//
	//# \param	type	The type of the sound source. See below for a list of possible types.
	//# \param	name	The name of the sound resource associated with the source.
	// 
	//# \desc
	//#  
	//# \table	SourceType 
	// 
	//# \base	Object		A source object is an object that can be shared by multiple source nodes.
	// 
	//# \also	$@Source@$
	
	
	//# \function	SourceObject::GetSourceType		Returns the specific type of a source. 
	//
	//# \proto	SourceType GetSourceType(void) const;
	//
	//# \desc 
	//# The $GetSourceType$ function returns the specific source type, which can be one of the following values.
	//
	//# \table	SourceType
	
	
	//# \function	SourceObject::GetSourceFlags		Returns the source flags.
	//
	//# \proto	unsigned_int32 GetSourceFlags(void) const;
	//
	//# \desc
	//# The $GetSourceFlags$ function returns the source flags, which can be a combination (through logical OR)
	//# of the following values.
	//
	//# \table	SourceFlags
	//
	//# \also	$@SourceObject::SetSourceFlags@$
	
	
	//# \function	SourceObject::SetSourceFlags		Sets the source flags.
	//
	//# \proto	void SetSourceFlags(unsigned_int32 flags);
	//
	//# \desc
	//# The $SetSourceFlags$ function sets the source flags to the value specified by the $flags$ parameter,
	//# which can be a combination (through logical OR) of the following values.
	//
	//# \table	SourceFlags
	//
	//# \also	$@SourceObject::GetSourceFlags@$
	
	
	class SourceObject : public Object
	{
		friend class WorldMgr;
		
		private:
			
			SourceType			sourceType;
			unsigned_int32		sourceFlags;
			
			float				initialSourceVolume;
			float				initialSourceFrequency;
			
			SoundGroupType		soundGroupType;
			
			List<SoundData>		soundList;
			
			static SourceObject *Construct(Unpacker& data, unsigned_int32 unpackFlags);
		
		protected:
			
			SourceObject(SourceType type);
			SourceObject(SourceType type, const char *name);
			~SourceObject();
		
		public:
			
			SourceType GetSourceType(void) const
			{
				return (sourceType);
			}
			
			unsigned_int32 GetSourceFlags(void) const
			{
				return (sourceFlags);
			}
			
			void SetSourceFlags(unsigned_int32 flags)
			{
				sourceFlags = flags;
			}
			
			float GetInitialSourceVolume(void) const
			{
				return (initialSourceVolume);
			}
			
			void SetInitialSourceVolume(float volume)
			{
				initialSourceVolume = volume;
			}
			
			float GetInitialSourceFrequency(void) const
			{
				return (initialSourceFrequency);
			}
			
			void SetInitialSourceFrequency(float frequency)
			{
				initialSourceFrequency = frequency;
			}
			
			SoundGroupType GetSoundGroupType(void) const
			{
				return (soundGroupType);
			}
			
			void SetSoundGroupType(SoundGroupType type)
			{
				soundGroupType = type;
			}
			
			SoundData *GetFirstSound(void) const
			{
				return (soundList.First());
			}
			
			void AddSound(const char *name)
			{
				soundList.Append(new SoundData(name));
			}
			
			void PurgeSounds(void)
			{
				soundList.Purge();
			}
			
			void PackType(Packer& data) const;
			void Pack(Packer& data, unsigned_int32 packFlags) const;
			void Unpack(Unpacker& data, unsigned_int32 unpackFlags);
			bool UnpackChunk(const ChunkHeader *chunkHeader, Unpacker& data, unsigned_int32 unpackFlags);
			void *BeginSettingsUnpack(void);
			
			int32 GetCategoryCount(void) const;
			Type GetCategoryType(int32 index, const char **title) const;
			int32 GetCategorySettingCount(Type category) const;
			Setting *GetCategorySetting(Type category, int32 index, unsigned_int32 flags) const;
			void SetCategorySetting(Type category, const Setting *setting);
	};
	
	
	//# \class	AmbientSourceObject		Encapsulates data pertaining to an ambient sound source.
	//
	//# The $AmbientSourceObject$ class encapsulates data pertaining to an ambient sound source.
	//
	//# \def	class AmbientSourceObject : public SourceObject
	//
	//# \ctor	AmbientSourceObject(const char *sound);
	//
	//# \param	sound	The name of the sound resource associated with the source.
	//
	//# \desc
	//
	//# \base	SourceObject		An $AmbientSourceObject$ is a specific type of $SourceObject$.
	//
	//# \also	$@AmbientSource@$
	
	
	class AmbientSourceObject : public SourceObject
	{
		friend class SourceObject;
		
		private:
			
			int32		fadeTime;
			int32		loopIndex;
			
			AmbientSourceObject();
			~AmbientSourceObject();
		
		public:
			
			AmbientSourceObject(const char *sound);
			
			int32 GetFadeTime(void) const
			{
				return (fadeTime);
			}
			
			void SetFadeTime(int32 time)
			{
				fadeTime = time;
			}
			
			int32 GetLoopIndex(void) const
			{
				return (loopIndex);
			}
			
			void SetLoopIndex(int32 index)
			{
				loopIndex = index;
			}
			
			void Pack(Packer& data, unsigned_int32 packFlags) const;
			void Unpack(Unpacker& data, unsigned_int32 unpackFlags);
			bool UnpackChunk(const ChunkHeader *chunkHeader, Unpacker& data, unsigned_int32 unpackFlags);
			
			int32 GetCategorySettingCount(Type category) const;
			Setting *GetCategorySetting(Type category, int32 index, unsigned_int32 flags) const;
			void SetCategorySetting(Type category, const Setting *setting);
	};
	
	
	//# \class	OmniSourceObject	Encapsulates data pertaining to an omnidirectional sound source.
	//
	//# The $OmniSourceObject$ class encapsulates data pertaining to an omnidirectional sound source.
	//
	//# \def	class OmniSourceObject : public SourceObject
	//
	//# \ctor	OmniSourceObject(const char *sound, float range);
	//
	//# \param	sound	The name of the sound resource associated with the source.
	//# \param	range	The range of the sound source.
	//
	//# \desc
	//
	//# \base	SourceObject		An $OmniSourceObject$ is a specific type of $SourceObject$.
	//
	//# \also	$@OmniSource@$
	
	
	//# \function	OmniSourceObject::GetSourceRange		Returns the source range.
	//
	//# \proto	float GetSourceRange(void) const;
	//
	//# \desc
	//
	//# \also	$@OmniSourceObject::SetSourceRange@$
	
	
	//# \function	OmniSourceObject::SetSourceRange		Sets the source range.
	//
	//# \proto	void SetSourceRange(float range);
	//
	//# \param	range	The new range of the source.
	//
	//# \desc
	//
	//# \also	$@OmniSourceObject::GetSourceRange@$
	
	
	class OmniSourceObject : public SourceObject
	{
		friend class SourceObject;
		
		private:
			
			float		sourceRange;
			
			float		reflectionVolume;
			float		reflectionHFVolume;
			
			OmniSourceObject();
			
			void Initialize(void);
		
		protected:
			
			OmniSourceObject(SourceType type);
			OmniSourceObject(SourceType type, const char *sound, float range);
			~OmniSourceObject();
		
		public:
			
			OmniSourceObject(const char *sound, float range);
			
			float GetSourceRange(void) const
			{
				return (sourceRange);
			}
			
			void SetSourceRange(float range)
			{
				sourceRange = range;
			}
			
			float GetReflectionVolume(void) const
			{
				return (reflectionVolume);
			}
			
			void SetReflectionVolume(float volume)
			{
				reflectionVolume = volume;
			}
			
			float GetReflectionHFVolume(void) const
			{
				return (reflectionHFVolume);
			}
			
			void SetReflectionHFVolume(float volume)
			{
				reflectionHFVolume = volume;
			}
			
			void Pack(Packer& data, unsigned_int32 packFlags) const;
			void Unpack(Unpacker& data, unsigned_int32 unpackFlags);
			bool UnpackChunk(const ChunkHeader *chunkHeader, Unpacker& data, unsigned_int32 unpackFlags);
			
			int32 GetCategorySettingCount(Type category) const;
			Setting *GetCategorySetting(Type category, int32 index, unsigned_int32 flags) const;
			void SetCategorySetting(Type category, const Setting *setting);
			
			int32 GetObjectSize(float *size) const;
			void SetObjectSize(const float *size);
	};
	
	
	//# \class	DirectedSourceObject	Encapsulates data pertaining to a directed sound source.
	//
	//# The $DirectedSourceObject$ class encapsulates data pertaining to a directed sound source.
	//
	//# \def	class DirectedSourceObject : public SourceObject
	//
	//# \ctor	DirectedSourceObject(const char *sound, float range, float apex);
	//
	//# \param	sound	The name of the sound resource associated with the source.
	//# \param	range	The range of the sound source.
	//# \param	apex	The tangent of half the apex angle for the sound source.
	//
	//# \desc
	//
	//# \base	SourceObject		A $DirectedSourceObject$ is a specific type of $SourceObject$
	//
	//# \also	$@DirectedSource@$
	
	
	//# \function	DirectedSourceObject::GetApexTangent		Returns the tangent of half the apex angle for a sound source.
	//
	//# \proto	float GetApexTangent(void) const;
	//
	//# \desc
	//
	//# \also	$@DirectedSourceObject::SetApexTangent@$
	
	
	//# \function	DirectedSourceObject::SetApexTangent		Sets the tangent of half the apex angle for a sound source.
	//
	//# \proto	void SetApexTangent(float apex);
	//
	//# \param	apex	The tangent of half the apex angle for the sound source.
	//
	//# \desc
	//
	//# \also	$@DirectedSourceObject::GetApexTangent@$
	
	
	class DirectedSourceObject : public OmniSourceObject
	{
		friend class SourceObject;
		
		private:
			
			float		apexTangent;
			
			float		outerConeVolume;
			float		outerConeHFVolume;
			
			DirectedSourceObject();
			~DirectedSourceObject();
		
		public:
			
			DirectedSourceObject(const char *sound, float range, float apex);
			
			float GetApexTangent(void) const
			{
				return (apexTangent);
			}
			
			void SetApexTangent(float apex)
			{
				apexTangent = apex;
			}
			
			float GetOuterConeVolume(void) const
			{
				return (outerConeVolume);
			}
			
			void SetOuterConeVolume(float volume)
			{
				outerConeVolume = volume;
			}
			
			float GetOuterConeHFVolume(void) const
			{
				return (outerConeHFVolume);
			}
			
			void SetOuterConeHFVolume(float volume)
			{
				outerConeHFVolume = volume;
			}
			
			void Pack(Packer& data, unsigned_int32 packFlags) const;
			void Unpack(Unpacker& data, unsigned_int32 unpackFlags);
			bool UnpackChunk(const ChunkHeader *chunkHeader, Unpacker& data, unsigned_int32 unpackFlags);
			
			int32 GetCategorySettingCount(Type category) const;
			Setting *GetCategorySetting(Type category, int32 index, unsigned_int32 flags) const;
			void SetCategorySetting(Type category, const Setting *setting);
			
			int32 GetObjectSize(float *size) const;
			void SetObjectSize(const float *size);
	};
	
	
	//# \class	Source	Represents a sound source node in a world.
	//
	//# The $Source$ class represents a sound source node in a world.
	//
	//# \def	class Source : public Node, public ListElement<Source>, public Completable<Source>
	//
	//# \ctor	Source(SourceType type, bool persistent);
	//
	//# The constructor has protected access. A $Source$ class can only exist as the base class for a more specific type of sound source.
	//
	//# \param	type		The type of the sound source. See below for a list of possible types.
	//# \param	persistent	A boolean value indicating whether the sound source persists after it plays.
	//
	//# \desc
	//#
	//# \table	SourceType
	//
	//# \base	Node							A $Source$ node is a scene graph node.
	//# \base	Utilities/ListElement<Source>	Used internally by the World Manager.
	//# \base	Utilities/Completable<Source>	The completion procedure is called when the sound finishes playing.
	//
	//# \also	$@SourceObject@$
	
	
	//# \function	Source::GetSourceType		Returns the specific type of a sound source.
	//
	//# \proto	SourceType GetSourceType(void) const;
	//
	//# \desc
	//# The $GetSourceType$ function returns the specific sound source type, which can be one of the following values.
	//
	//# \table	SourceType
	
	
	class Source : public Node, public ListElement<Source>, public Completable<Source>
	{
		friend class Node;
		friend class World;
		
		private:
			
			SourceType			sourceType;
			
			int32				sourceDuration;
			int32				sourceLifeTime;
			
			float				sourceVolume;
			float				sourceFrequency;
			
			DeferredTask		playTask;
			
			void Initialize(void);
			
			static Source *Construct(Unpacker& data, unsigned_int32 unpackFlags);
			
			void LoadSound(void);
			
			static void SoundComplete(Sound *sound, void *cookie);
			static void PlayTask(DeferredTask *task, void *cookie);
		
		protected:
			
			unsigned_int32		sourceState;
			
			ZoneRegion			*rootRegion;
			Sound				*sourceSound;
			
			Source(SourceType type);
			Source(SourceType type, bool persistent);
			Source(const Source& source);
			
			virtual void InitializeSound(Sound *sound);
			virtual void ResetSound(void);
		
		public:
			
			virtual ~Source();
			
			using ListElement<Source>::Previous;
			using ListElement<Source>::Next;
			
			SourceType GetSourceType(void) const
			{
				return (sourceType);
			}
			
			SourceObject *GetObject(void) const
			{
				return (static_cast<SourceObject *>(Node::GetObject()));
			}
			
			bool Playing(void) const
			{
				return ((sourceState & kSourcePlaying) != 0);
			}
			
			float GetSourceVolume(void) const
			{
				return (sourceVolume);
			}
			
			float GetSourceFrequency(void) const
			{
				return (sourceFrequency);
			}
			
			void InvalidateSourceRegions(void)
			{
				Invalidate();
			}
			
			void PackType(Packer& data) const;
			void Pack(Packer& data, unsigned_int32 packFlags) const;
			void Unpack(Unpacker& data, unsigned_int32 unpackFlags);
			bool UnpackChunk(const ChunkHeader *chunkHeader, Unpacker& data, unsigned_int32 unpackFlags);
			
			void Preprocess(void);
			void Neutralize(void);
			void Move(void);
			
			C4API virtual void Play(void);
			C4API virtual void Stop(void);
			
			virtual bool Engage(void);
			virtual void Disengage(void);
			
			C4API void SetSourceVolume(float volume);
			C4API void SetSourceFrequency(float frequency);
	};
	
	
	//# \class	AmbientSource	Represents an ambient sound source node in a world.
	//
	//# The $AmbientSource$ class represents an ambient sound source node in a world.
	//
	//# \def	class AmbientSource : public Source
	//
	//# \ctor	AmbientSource(const char *name, bool persistent = false);
	//
	//# \param	name		The name of the sound resource associated with the source.
	//# \param	persistent	A boolean value indicating whether the sound source persists after it plays.
	//
	//# \desc
	//#
	//
	//# \base	Source		An $AmbientSource$ node is a specific type of $Source$.
	//
	//# \also	$@AmbientSourceObject@$
	
	
	class AmbientSource : public Source
	{
		friend class Source;
		
		private:
			
			AmbientSource();
			AmbientSource(const AmbientSource& ambientSource);
			
			Node *Replicate(void) const override;
			
			void InitializeSound(Sound *sound);
		
		public:
			
			C4API AmbientSource(const char *name, bool persistent = false);
			C4API ~AmbientSource();
			
			AmbientSourceObject *GetObject(void) const
			{
				return (static_cast<AmbientSourceObject *>(Node::GetObject()));
			}
			
			void Preprocess(void);
			
			void Play(void);
			bool Engage(void);
			
			C4API void FadeOut(int32 time);
			C4API Sound *ExtractSound(void);
	};
	
	
	//# \class	OmniSource	Represents an omnidirectional sound source node in a world.
	//
	//# The $OmniSource$ class represents an omnidirectional sound source node in a world.
	//
	//# \def	class OmniSource : public Source
	//
	//# \ctor	OmniSource(const char *name, float range, bool persistent = false);
	//
	//# \param	name		The name of the sound resource associated with the source.
	//# \param	range		The range of the sound source.
	//# \param	persistent	A boolean value indicating whether the sound source persists after it plays.
	//
	//# \desc
	//#
	//
	//# \base	Source		An $OmniSource$ node is a specific type of $Source$.
	//
	//# \also	$@OmniSourceObject@$
	
	
	class OmniSource : public Source
	{
		friend class Source;
		
		private:
			
			float						sourceRange;
			Vector3D					sourceVelocity;
			
			SoundRoom					*sourceRoom;
			const AcousticsProperty		*sourceObstruction;
			
			int32						playRegionCount;
			const SourceRegion			*playRegion[kMaxSoundPathCount];
			
			OmniSource();
			
			Node *Replicate(void) const override;
			
			void CalculatePostBounding(void) override;
			
			void CalculatePermeation(SourceRegion *region);
			void DetectObstruction(void);
		
		protected:
			
			OmniSource(SourceType type);
			OmniSource(SourceType type, bool persistent);
			OmniSource(const OmniSource& omniSource);
			
			void InitializeSound(Sound *sound);
			void ResetSound(void);
		
		public:
			
			C4API OmniSource(const char *name, float range, bool persistent = false);
			C4API ~OmniSource();
			
			OmniSourceObject *GetObject(void) const
			{
				return (static_cast<OmniSourceObject *>(Node::GetObject()));
			}
			
			float GetSourceRange(void) const
			{
				return (sourceRange);
			}
			
			void Pack(Packer& data, unsigned_int32 packFlags) const;
			void Unpack(Unpacker& data, unsigned_int32 unpackFlags);
			bool UnpackChunk(const ChunkHeader *chunkHeader, Unpacker& data, unsigned_int32 unpackFlags);
			
			void Preprocess(void);
			void EnterZone(Zone *zone);
			
			C4API void Play(void);
			void Disengage(void);
			
			void BeginUpdate(void);
			void EndUpdate(void);
			
			void AddPlayRegion(SourceRegion *region, const Point3D& listenerPosition);
			
			C4API void SetSourceVelocity(const Vector3D& velocity);
	};
	
	
	//# \class	DirectedSource	Represents a directed sound source node in a world.
	//
	//# The $DirectedSource$ class represents a directed sound source node in a world.
	//
	//# \def	class DirectedSource : public Source
	//
	//# \ctor	DirectedSource(const char *name, float range, float apex, bool persistent = false);
	//
	//# \param	name		The name of the sound resource associated with the source.
	//# \param	range		The range of the sound source.
	//# \param	apex		The tangent of half the apex angle for the sound source.
	//# \param	persistent	A boolean value indicating whether the sound source persists after it plays.
	//
	//# \desc
	//#
	//
	//# \base	Source		A $DirectedSource$ node is a specific type of $Source$.
	//
	//# \also	$@DirectedSourceObject@$
	
	
	class DirectedSource : public OmniSource
	{
		friend class Source;
		
		private:
			
			DirectedSource();
			DirectedSource(const DirectedSource& directedSource);
			
			Node *Replicate(void) const override;
			
			void InitializeSound(Sound *sound);
		
		public:
			
			C4API DirectedSource(const char *name, float range, float apex, bool persistent = false);
			C4API ~DirectedSource();
			
			DirectedSourceObject *GetObject(void) const
			{
				return (static_cast<DirectedSourceObject *>(Node::GetObject()));
			}
	};
}


#endif

// ZYURVUR
