<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <UnityWSASolutionName>Holo</UnityWSASolutionName>
        <UnityWSASolutionDir>C:\Work\UnE\Unity\Holo\HoloLens\</UnityWSASolutionDir>
        <UnityProjectDir>C:\Work\UnE\Unity\Holo\</UnityProjectDir>
        <UnityWSAPlayerDir>C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\</UnityWSAPlayerDir>
        <UnityWSAToolsDir>$(UnityWSASolutionDir)Unity\Tools\</UnityWSAToolsDir>
    </PropertyGroup>
</Project>
