<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <Keyword>Win32Proj</Keyword>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <LinkIncremental>true</LinkIncremental>
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <TargetName>ssleay32d</TargetName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <LinkIncremental>true</LinkIncremental>
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <TargetName>ssleay32d</TargetName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <LinkIncremental>true</LinkIncremental>
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <TargetName>ssleay32</TargetName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <LinkIncremental>true</LinkIncremental>
    <OutDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</OutDir>
    <IntDir>$(UNE_HOME)\tmp\$(PlatformToolset)\$(PlatformName)\$(Configuration)\$(ProjectName)\</IntDir>
    <TargetName>ssleay32</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
      <PreprocessorDefinitions>WIN32;_DEBUG;_WINDOWS;_USRDLL;OPENSSL_EXPORTS;OPENSSL_THREADS;DSO_WIN32;OPENSSL_SYSNAME_WIN32;WIN32_LEAN_AND_MEAN;L_ENDIAN;_CRT_SECURE_NO_DEPRECATE;OPENSSL_USE_APPLINK;OPENSSL_NO_RC5;OPENSSL_NO_MD2;OPENSSL_NO_KRB5;OPENSSL_NO_JPAKE;OPENSSL_NO_STATIC_ENGINE;OPENSSL_BUILD_SHLIBSSL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <Optimization>Disabled</Optimization>
      <AdditionalIncludeDirectories>..\..\include\inc32;..\..\src\OpenSSL\engines;..\..\src\OpenSSL\Crypto;..\..\src\OpenSSL;..\..\src\OpenSSL\ssl;..\..\src\OpenSSL\Crypto\asn1;..\..\src\OpenSSL\Crypto\evp;..\..\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <TargetMachine>MachineX86</TargetMachine>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Windows</SubSystem>
      <AdditionalDependencies>libeay32d.lib;ws2_32.lib;gdi32.lib;advapi32.lib;crypt32.lib;user32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <ModuleDefinitionFile>..\..\src\OpenSSL\ms\ssleay32.def</ModuleDefinitionFile>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib</AdditionalLibraryDirectories>
      <ImportLibrary>$(OutDir)\$(TargetName).lib</ImportLibrary>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName)10$(PlatformName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName)10$(PlatformName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <PreprocessorDefinitions>WIN32;_DEBUG;_WINDOWS;_USRDLL;OPENSSL_EXPORTS;OPENSSL_THREADS;DSO_WIN32;OPENSSL_SYSNAME_WIN32;WIN32_LEAN_AND_MEAN;L_ENDIAN;_CRT_SECURE_NO_DEPRECATE;OPENSSL_USE_APPLINK;OPENSSL_NO_RC5;OPENSSL_NO_MD2;OPENSSL_NO_KRB5;OPENSSL_NO_JPAKE;OPENSSL_NO_STATIC_ENGINE;OPENSSL_BUILD_SHLIBSSL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <Optimization>Disabled</Optimization>
      <AdditionalIncludeDirectories>..\..\include\inc64;..\..\src\OpenSSL\engines;..\..\src\OpenSSL\Crypto;..\..\src\OpenSSL;..\..\src\OpenSSL\ssl;..\..\src\OpenSSL\Crypto\asn1;..\..\src\OpenSSL\Crypto\evp;..\..\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Windows</SubSystem>
      <AdditionalDependencies>libeay32d.lib;ws2_32.lib;gdi32.lib;advapi32.lib;crypt32.lib;user32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <ModuleDefinitionFile>..\..\src\OpenSSL\ms\ssleay32.def</ModuleDefinitionFile>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib64</AdditionalLibraryDirectories>
      <ImportLibrary>$(OutDir)\$(TargetName).lib</ImportLibrary>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName)10$(PlatformName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName)10$(PlatformName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <ClCompile>
      <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;_USRDLL;OPENSSL_EXPORTS;OPENSSL_THREADS;DSO_WIN32;OPENSSL_SYSNAME_WIN32;WIN32_LEAN_AND_MEAN;L_ENDIAN;_CRT_SECURE_NO_DEPRECATE;OPENSSL_USE_APPLINK;OPENSSL_NO_RC5;OPENSSL_NO_MD2;OPENSSL_NO_KRB5;OPENSSL_NO_JPAKE;OPENSSL_NO_STATIC_ENGINE;OPENSSL_BUILD_SHLIBSSL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <AdditionalIncludeDirectories>..\..\include\inc32;..\..\src\OpenSSL\engines;..\..\src\OpenSSL\Crypto;..\..\src\OpenSSL;..\..\src\OpenSSL\ssl;..\..\src\OpenSSL\Crypto\asn1;..\..\src\OpenSSL\Crypto\evp;..\..\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <TargetMachine>MachineX86</TargetMachine>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Windows</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <ModuleDefinitionFile>..\..\src\OpenSSL\ms\ssleay32.def</ModuleDefinitionFile>
      <AdditionalDependencies>libeay32.lib;ws2_32.lib;gdi32.lib;advapi32.lib;crypt32.lib;user32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <ImportLibrary>$(OutDir)\$(TargetName).lib</ImportLibrary>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib</AdditionalLibraryDirectories>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;_USRDLL;OPENSSL_EXPORTS;OPENSSL_THREADS;DSO_WIN32;OPENSSL_SYSNAME_WIN32;WIN32_LEAN_AND_MEAN;L_ENDIAN;_CRT_SECURE_NO_DEPRECATE;OPENSSL_USE_APPLINK;OPENSSL_NO_RC5;OPENSSL_NO_MD2;OPENSSL_NO_KRB5;OPENSSL_NO_JPAKE;OPENSSL_NO_STATIC_ENGINE;OPENSSL_BUILD_SHLIBSSL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <AdditionalIncludeDirectories>..\..\include\inc64;..\..\src\OpenSSL\engines;..\..\src\OpenSSL\Crypto;..\..\src\OpenSSL;..\..\src\OpenSSL\ssl;..\..\src\OpenSSL\Crypto\asn1;..\..\src\OpenSSL\Crypto\evp;..\..\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Windows</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <ModuleDefinitionFile>..\..\src\OpenSSL\ms\ssleay32.def</ModuleDefinitionFile>
      <AdditionalDependencies>libeay32.lib;ws2_32.lib;gdi32.lib;advapi32.lib;crypt32.lib;user32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <ImportLibrary>$(OutDir)\$(TargetName).lib</ImportLibrary>
      <AdditionalLibraryDirectories>$(UNE_HOME)\esdk\lib64</AdditionalLibraryDirectories>
    </Link>
    <PostBuildEvent>
      <Command>GOTO :$(ConfigurationName)
:Release
if $(PlatformName)==x64 goto :x64r
:win32r
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName).lib
goto :exit
:x64r
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName).lib
goto :exit
:Debug
if $(PlatformName)==x64 goto :x64d
:win32d
copy $(TargetPath) $(UNE_HOME)\bin\common\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common\$(TargetName).pdb
goto :exit
:x64d
copy $(TargetPath) $(UNE_HOME)\bin\common64\$(TargetName).dll
copy $(TargetDir)\$(TargetName).lib $(UNE_HOME)\esdk\lib64\$(TargetName).lib
copy $(TargetDir)\$(TargetName).pdb $(UNE_HOME)\bin\common64\$(TargetName).pdb
:exit
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="..\..\src\OpenSSL\ssl\s2_meth.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s2_srvr.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s2_clnt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s2_lib.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s2_enc.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s2_pkt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_meth.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_srvr.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_clnt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_lib.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_enc.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_pkt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s3_both.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s23_meth.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s23_srvr.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s23_clnt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s23_lib.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\s23_pkt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\t1_meth.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\t1_srvr.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\t1_clnt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\t1_lib.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\t1_enc.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_meth.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_srvr.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_clnt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_lib.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_pkt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_both.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\d1_enc.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_lib.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_err2.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_cert.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_sess.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_ciph.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_stat.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_rsa.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_asn1.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_txt.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_algs.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\bio_ssl.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\ssl_err.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\kssl.c" />
    <ClCompile Include="..\..\src\OpenSSL\ssl\t1_reneg.c" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\src\OpenSSL\ms\ssleay32.def" />
    <None Include="..\..\src\OpenSSL\ms\uptable.asm" />
  </ItemGroup>
  <ItemGroup>
    <ResourceCompile Include="..\..\src\OpenSSL\ms\version32.rc" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>