//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUtility2.DownloadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DownloadService.IDownload")]
    public interface IDownload {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/Download", ReplyAction="http://tempuri.org/IDownload/DownloadResponse")]
        DBUtility2.DownloadService.DownloadResponse Download(DBUtility2.DownloadService.DownloadRequest request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/Download", ReplyAction="http://tempuri.org/IDownload/DownloadResponse")]
        System.Threading.Tasks.Task<DBUtility2.DownloadService.DownloadResponse> DownloadAsync(DBUtility2.DownloadService.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/GetFileSegmentCount", ReplyAction="http://tempuri.org/IDownload/GetFileSegmentCountResponse")]
        string[] GetFileSegmentCount(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/GetFileSegmentCount", ReplyAction="http://tempuri.org/IDownload/GetFileSegmentCountResponse")]
        System.Threading.Tasks.Task<string[]> GetFileSegmentCountAsync(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/GetFolder", ReplyAction="http://tempuri.org/IDownload/GetFolderResponse")]
        bool GetFolder(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/GetFolder", ReplyAction="http://tempuri.org/IDownload/GetFolderResponse")]
        System.Threading.Tasks.Task<bool> GetFolderAsync(string path);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string filePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int segmentIndex;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string filePath, int segmentIndex) {
            this.filePath = filePath;
            this.segmentIndex = segmentIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] DownloadResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int readCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorMessage;
        
        public DownloadResponse() {
        }
        
        public DownloadResponse(byte[] DownloadResult, int readCount, string errorMessage) {
            this.DownloadResult = DownloadResult;
            this.readCount = readCount;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDownloadChannel : DBUtility2.DownloadService.IDownload, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadClient : System.ServiceModel.ClientBase<DBUtility2.DownloadService.IDownload>, DBUtility2.DownloadService.IDownload {
        
        public DownloadClient() {
        }
        
        public DownloadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownloadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DBUtility2.DownloadService.DownloadResponse DBUtility2.DownloadService.IDownload.Download(DBUtility2.DownloadService.DownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public byte[] Download(string filePath, int segmentIndex, out int readCount, out string errorMessage) {
            DBUtility2.DownloadService.DownloadRequest inValue = new DBUtility2.DownloadService.DownloadRequest();
            inValue.filePath = filePath;
            inValue.segmentIndex = segmentIndex;
            DBUtility2.DownloadService.DownloadResponse retVal = ((DBUtility2.DownloadService.IDownload)(this)).Download(inValue);
            readCount = retVal.readCount;
            errorMessage = retVal.errorMessage;
            return retVal.DownloadResult;
        }
        
        public System.Threading.Tasks.Task<DBUtility2.DownloadService.DownloadResponse> DownloadAsync(DBUtility2.DownloadService.DownloadRequest request) {
            return base.Channel.DownloadAsync(request);
        }
        
        public string[] GetFileSegmentCount(string filePath) {
            return base.Channel.GetFileSegmentCount(filePath);
        }
        
        public System.Threading.Tasks.Task<string[]> GetFileSegmentCountAsync(string filePath) {
            return base.Channel.GetFileSegmentCountAsync(filePath);
        }
        
        public bool GetFolder(string path) {
            return base.Channel.GetFolder(path);
        }
        
        public System.Threading.Tasks.Task<bool> GetFolderAsync(string path) {
            return base.Channel.GetFolderAsync(path);
        }
    }
}
