<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SOPManager\SOPManager.Model\SOPManager.Model.csproj" />
    <ProjectReference Include="..\Dashboard.IDAL\Dashboard.IDAL.csproj" />
    <ProjectReference Include="..\Dashboard.Model\Dashboard.Model.csproj" />
  </ItemGroup>

</Project>
