; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "KPX 모바일 관리자"
#define MyAppVersion "1.0"
#define MyAppPublisher "UNE, Inc."
#define MyAppURL "http://www.unes.co.kr/"
#define MyAppExeName "KpxUserAcceptance.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5D5CE964-1107-4B10-99A3-C983BF33191D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=\UNE\{#MyAppName}
DefaultGroupName=\UNE\{#MyAppName}
OutputDir=D:\Installer\output
OutputBaseFilename=KPX_모바일_관리자
SetupIconFile=D:\Installer\uninstallicon.ico
Compression=lzma
SolidCompression=yes
UninstallFilesDir={app}

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: D:\KPX\Admin\DBUtil.dll; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\KpxUserAcceptance.exe; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\libSMS.dll; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\Newtonsoft.Json.dll; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\iconv.dll; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\libxml2.dll; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\zlib1.dll; DestDir: {app}; Components: FULL; Flags: ignoreversion recursesubdirs createallsubdirs overwritereadonly
Source: D:\KPX\Admin\ezSMSComponent32.dll; DestDir: {app}; Components: FULL; Flags: regserver overwritereadonly;

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}; WorkingDir: {app}\{#MyAppName}; Languages:

[InstallDelete]
Name: {app}\*.*; Type: filesandordirs

[UninstallDelete]
Name: {app}\*.*; Type: files

[Types] 
Name: FULL; Description: 전체 설치

[Components] 
Name: FULL; Description: "전체 설치"; Types: FULL; ExtraDiskSpaceRequired: 0; Flags: fixed; 