; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "상황인지용 플로챠트 시나리오 생성기"
#define MyAppVersion "1.0"
#define MyAppPublisher "UNE, Inc."
#define MyAppURL "http://www.unes.co.kr/"
#define MyAppExeName "ScenarioMaker.exe"

[Setup]
#define MyDateTimeString GetDateTimeString('yyyy.mm.dd_hhnnss', '-', ':');
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=\UNE\{#MyAppName}
DefaultGroupName=\UNE\{#MyAppName}
OutputDir=D:\Installer\output
OutputBaseFilename="SensorSimulationScenarioMaker_{#MyDateTimeString}"
SetupIconFile=D:\Installer\uninstallicon.ico
Compression=lzma
SolidCompression=yes
UninstallFilesDir={app}

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; DLL
Source: ..\bin\common12\Geometry.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\GeometryDn.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\IronPython.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\IronPython.Modules.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\libPropertyDn.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\libSection.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\Microsoft.CSharp.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\Microsoft.Dynamic.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\Microsoft.Scripting.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\Microsoft.Scripting.Metadata.dll; DestDir: {app}; Components: FULL;
source: ..\bin\common12\UEControl.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKBRep.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKernel.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKernel.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKG2d.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKG3d.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKGeomAlgo.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKGeomBase.dll; DestDir: {app}; Components: FULL;
Source: ..\bin\common12\OpenCASCADE6.7.1\TKMath.dll; DestDir: {app}; Components: FULL;

; EXE
Source: ..\bin\common12\ScenarioMaker.exe; DestDir: {app}; Components: FULL;

; FILE
Source: D:\Installer\vcredist_x86.exe; DestDir: {app}; Components: FULL;
Source: D:\Installer\vcredist_x86_2013.exe; DestDir: {app}; Components: FULL;
Source: D:\Installer\vcredist_2008_x86.exe; DestDir: {app}; Components: FULL;

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}; WorkingDir: {app}\{#MyAppName}; Languages:

[Run]
Filename: {app}\vcredist_2008_x86.exe; Description: "{#MyAppName} 실행에 필요한 필수 구성요소를 설치합니다.";
Filename: {app}\vcredist_x86.exe; Description: "{#MyAppName} 실행에 필요한 필수 구성요소를 설치합니다.";
Filename: {app}\vcredist_x86_2013.exe; Description: "{#MyAppName} 실행에 필요한 필수 구성요소를 설치합니다.";
;Filename: msiexec.exe; Parameters: "/i""{app}\MSSpeech_TTS_ko-KR_Heami.msi"" /qn";
;Filename: msiexec.exe; Parameters: "/i""{app}\SpeechPlatformRuntime.msi"" /qn";

[InstallDelete]
Name: {app}\*.*; Type: filesandordirs

[UninstallDelete]
Name: {app}\*.*; Type: files

[Types] 
Name: FULL; Description: 전체 설치

[Components] 
Name: FULL; Description: "전체 설치"; Types: FULL; ExtraDiskSpaceRequired: 0; Flags: fixed; 
